// Explicit local browser smoke; backend must be build27_runtime.py and frontend in development-auth mode.
import {createRequire} from 'node:module';
const require=createRequire(new URL('../../frontend/package.json',import.meta.url));
const {chromium}=require('@playwright/test');
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const context=await browser.newContext({acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
const accessibility=async()=>{await page.addScriptTag({content:require('axe-core').source});const result=await page.evaluate(async()=>await axe.run(document.querySelector('main'),{rules:{'color-contrast':{enabled:false},region:{enabled:false}}}));if(result.violations.length)throw Error('Accessibility: '+result.violations.map(v=>v.id).join(','));for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Page overflow');}};
const button=(name)=>page.getByRole('button',{name,exact:true});
const keyboard=async locator=>{await locator.focus();await page.keyboard.press('Enter');};
const goto=async path=>{await page.goto('http://127.0.0.1:3000'+path);await page.getByRole('main').waitFor();};
const download=async name=>{const waiting=page.waitForEvent('download');await keyboard(button(name));const d=await waiting;if(await d.failure())throw Error('Download failed');};
try{
 await page.goto('http://127.0.0.1:3000/login');await keyboard(button('Open workspace'));
 await page.getByRole('heading',{name:'A clear view of your work'}).waitFor();
 await goto('/library/upload');await page.getByLabel('Academic file').setInputFiles({name:'Synthetic PCA.pdf',mimeType:'application/pdf',buffer:Buffer.from('Synthetic PCA projects data onto directions of greatest variance. '.repeat(30))});
 for(const [label,value] of Object.entries({Course:'ML',Semester:'S1',Subject:'ML',Unit:'Unit 1'}))await page.getByLabel(label,{exact:true}).fill(value);
 await keyboard(button('Upload material'));await page.getByText('Material registered: Synthetic PCA.pdf').waitFor();
 await goto('/courses/ML');await page.getByRole('heading',{name:'ML',exact:true}).waitFor();await keyboard(page.locator('summary').filter({hasText:/^ML$/}));await keyboard(page.getByRole('link',{name:'Ask about this unit'}));
 await page.getByLabel('What would you like to understand?').fill('Explain PCA');await keyboard(button('Ask question'));await page.getByRole('heading',{name:'Grounded answer',exact:true}).waitFor();await accessibility();
 await goto('/assessment?course=ML&semester=S1&subject=ML&unit=Unit%201');await keyboard(button('Generate assessment'));await page.getByLabel('Question 1 text').waitFor();await page.getByLabel('Question 1 text').fill('Professor revised PCA question?');await keyboard(button('Validate professor edits'));await page.getByText('Professor edits validated.',{exact:false}).waitFor();await download('Export DOCX');await accessibility();
 await goto('/documents');await page.getByLabel('Document type',{exact:true}).selectOption('notice');await page.getByLabel('Purpose / drafting instructions').fill('Announce a synthetic seminar.');await page.getByLabel('Title (optional)',{exact:true}).fill('Synthetic seminar');await page.getByLabel('Date (optional)',{exact:true}).fill('10 October 2026');await keyboard(button('Generate document'));
 await page.getByLabel('Edit date',{exact:true}).waitFor();await page.getByLabel('Edit date',{exact:true}).fill('12 October 2026');await keyboard(button('Save document'));await page.getByRole('heading',{name:'Confirmed fact conflict'}).waitFor();await keyboard(button('Update confirmed facts and apply edit'));await page.getByText('Confirmed facts updated explicitly and edit applied.',{exact:false}).waitFor();await keyboard(button('Save document'));await page.getByText('Document and coherent version history saved privately.',{exact:false}).waitFor();await download('Export DOCX');await accessibility();
 await goto('/students');await page.getByLabel(/Student spreadsheet/).setInputFiles({name:'synthetic.csv',mimeType:'text/csv',buffer:Buffer.from('ID,Name,Attendance,Quiz\nIDMARKER27,STUDENTMARKER27,83.456,47.123\n')});await page.getByRole('heading',{name:'Data preview'}).waitFor();await page.getByLabel('Student identifier / roll number').selectOption('ID');await page.getByLabel('Student name',{exact:true}).selectOption('Name');await page.getByLabel('Attendance column').selectOption('Attendance');await page.getByRole('checkbox',{name:'Quiz',exact:true}).check();await keyboard(button('Validate and analyze'));await page.getByRole('heading',{name:'Class Overview'}).waitFor();await download('Export applied view CSV');await accessibility();
 await goto('/assistant');await page.getByLabel('Professor request').fill('Draft a short notice about a seminar.');await keyboard(button('Review plan'));await page.getByRole('heading',{name:'Plan validated'}).waitFor();await page.getByLabel('I approve this exact plan for execution.').check();await keyboard(button('Execute approved plan'));await keyboard(button('Open in Document Studio'));await page.getByLabel('Document body (blank lines separate paragraphs)').waitFor();
 await goto('/activity');await page.getByRole('list',{name:'Recent workspace actions'}).waitFor();await accessibility();if((await page.textContent('main')).includes('STUDENTMARKER27'))throw Error('Activity privacy failure');
 for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Page overflow');}
 await page.screenshot({path:'/private/tmp/build27-activity.png'});
 // Failure/recovery journey: invalid file, missing handles, and actual session revocation.
 await goto('/library/upload');await page.getByLabel('Academic file').setInputFiles({name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('synthetic')});await keyboard(button('Upload material'));await page.getByRole('alert').waitFor();
 await goto('/knowledge?workspace=expired');await page.getByText('Knowledge scope unavailable').waitFor();await keyboard(page.getByRole('link',{name:'Start a new question'}));await page.getByLabel('What would you like to understand?').waitFor();
 await goto('/assessment?workspace=expired');await page.getByText('Assessment workspace unavailable').waitFor();await keyboard(page.getByRole('link',{name:'Start a new assessment'}));await button('Generate assessment').waitFor();
 const csrf=await context.request.get('http://127.0.0.1:3000/api/v1/auth/csrf');await context.request.post('http://127.0.0.1:3000/api/v1/auth/logout',{headers:{'X-CSRF-Token':(await csrf.json()).csrf_token},data:{}});await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForURL('**/login');
 if(errors.length)throw Error(errors.join('\n'));console.log('PASS: integrated and failure/recovery journeys; keyboard controls; responsive activity; zero page errors; mocked inference only.');
}catch(e){await page.screenshot({path:'/private/tmp/build27-failure.png'});console.error('Browser smoke failed; synthetic screenshot saved outside repository.');throw e;}finally{await browser.close();}
