import { describe,it,expect,vi } from "vitest";
import { APIClient,APIError,parseError } from "@/lib/api";
function reply(value:unknown,status=200){return new Response(JSON.stringify(value),{status,headers:{"Content-Type":"application/json"}});}
describe("safe typed API boundary",()=>{
  it.each([401,403,404,409,422,503,500])("sanitizes %i errors",async(status)=>{const error=await parseError(reply({error:{code:"REQUEST_FAILED",message:"SQL /private/path TOKEN student marks",request_id:"secret"}},status));expect(error).toBeInstanceOf(APIError);expect(error.message).not.toMatch(/SQL|private|TOKEN|marks/);expect(error.requestId).toBeUndefined();});
  it("handles non-JSON errors",async()=>{const error=await parseError(new Response("Traceback SQL",{status:500}));expect(error.message).not.toMatch(/Traceback|SQL/);});
  it("includes credentials and backend CSRF token on mutations",async()=>{const transport=vi.fn().mockResolvedValueOnce(reply({csrf_token:"csrf-one"})).mockResolvedValueOnce(reply({answer:"PCA",grounded:true,sources:[]}));const client=new APIClient(transport);await client.answer({question:"PCA",filters:{}});expect(transport.mock.calls[0][0]).toBe("/api/v1/auth/csrf");expect(transport.mock.calls[1][1]).toMatchObject({credentials:"include",method:"POST",headers:{"X-CSRF-Token":"csrf-one"}});});
  it("uses login token without storing credentials",async()=>{const write=vi.spyOn(Storage.prototype,"setItem");const transport=vi.fn().mockResolvedValueOnce(reply({csrf_token:"login-csrf"})).mockResolvedValueOnce(reply({status:"signed_out"}));const client=new APIClient(transport);await client.login("professor-a");await client.logout();expect(transport.mock.calls[1][1].headers["X-CSRF-Token"]).toBe("login-csrf");expect(write).not.toHaveBeenCalled();});
  it("refreshes a rejected CSRF token once",async()=>{const transport=vi.fn().mockResolvedValueOnce(reply({csrf_token:"old"})).mockResolvedValueOnce(reply({error:{code:"CSRF_REJECTED"}},403)).mockResolvedValueOnce(reply({csrf_token:"new"})).mockResolvedValueOnce(reply({answer:"PCA",grounded:true,sources:[]}));await new APIClient(transport).answer({question:"PCA",filters:{}});expect(transport).toHaveBeenCalledTimes(4);expect(transport.mock.calls[3][1].headers["X-CSRF-Token"]).toBe("new");});
  it("does not automatically repeat failed generation",async()=>{const transport=vi.fn().mockResolvedValueOnce(reply({csrf_token:"csrf"})).mockResolvedValueOnce(reply({error:{code:"PROVIDER_UNAVAILABLE"}},503));await expect(new APIClient(transport).answer({question:"PCA",filters:{}})).rejects.toMatchObject({status:503});expect(transport).toHaveBeenCalledTimes(2);});
  it("signals session expiry",async()=>{const transport=vi.fn().mockResolvedValue(reply({error:{code:"UNAUTHENTICATED"}},401));const client=new APIClient(transport);const expire=vi.fn();client.subscribeUnauthorized(expire);await expect(client.me()).rejects.toMatchObject({status:401});expect(expire).toHaveBeenCalledOnce();});
  it("supports cancellation",async()=>{const signal=new AbortController().signal;const transport=vi.fn().mockRejectedValue(new DOMException("Cancelled","AbortError"));await expect(new APIClient(transport).me(signal)).rejects.toMatchObject({name:"AbortError"});expect(transport.mock.calls[0][1].signal).toBe(signal);});
  it("maps network failures safely",async()=>{await expect(new APIClient(vi.fn().mockRejectedValue(new Error("private upstream URL"))).me()).rejects.toMatchObject({status:0,code:"NETWORK_ERROR"});});
});
