import React from 'react';
import {beforeEach,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import axe from 'axe-core';
import {APIClient} from '@/lib/api';
import {AuthProvider} from '@/features/auth';
import {AssessmentPage} from '@/features/assessment';
const nav=vi.hoisted(()=>({params:new URLSearchParams()}));vi.mock('next/navigation',()=>({useSearchParams:()=>nav.params,usePathname:()=>'/assessment',useRouter:()=>({replace:vi.fn()})}));vi.mock('next/link',()=>({default:({href,children,...p}:{href:string}&React.ComponentProps<'a'>)=><a href={href} {...p}>{children}</a>}));
const material={material_id:'11111111-1111-4111-8111-111111111111',filename:'Synthetic PCA.pdf',course:'C',semester:'S',subject:'ML',unit:'U1',created_at:'2026-10-05'};
const assessment={handle:'private-workspace',title:'Synthetic Assessment',assessment_type:'Quiz',total_marks:2,revision:0,professor_edited:false,validation:{structure:true,marks:true},questions:[1,2].map(i=>({question_number:i,question_type:'MCQ',question_text:`Synthetic question ${i}?`,options:{A:'Projection',B:'Storage',C:'Deletion',D:'Attendance'},correct_answer:'A',model_answer:'A synthetic reference answer.',difficulty:'Easy',bloom_level:'Remember',marks:1}))};
function api(opts:{empty?:boolean;status?:number;category?:string;editFailure?:boolean;pending?:boolean}={}){let current=structuredClone(assessment);const transport=vi.fn(async(path:RequestInfo|URL,init?:RequestInit)=>{let data:unknown={};let status=200;const url=String(path);
 if(url.endsWith('/auth/me'))data={professor_id:'synthetic',display_name:'Synthetic Professor',institution_id:'institute',department_id:'department'};
 else if(url.endsWith('/auth/csrf'))data={csrf_token:'synthetic-csrf'};
 else if(url.endsWith('/materials'))data=opts.empty?[]:[material];
 else if(url.endsWith('/assessments/pyq'))data={handle:'private-pyq'};
 else if(url.endsWith('/assessments/generate')){if(opts.pending)return new Promise<Response>((_,reject)=>init?.signal?.addEventListener('abort',()=>reject(new DOMException('Stopped','AbortError'))));status=opts.status??200;data=status===200?current:{error:{code:opts.status===401?'UNAUTHENTICATED':'VALIDATION_ERROR',diagnostic:{category:opts.category??'PRODUCT_VALIDATION_FAILED',professor_message:'RAW PRIVATE /path secret'}}};}
 else if(url.endsWith('/assessments/private-workspace')&&(!init?.method||init.method==='GET'))data=current;
 else if(url.includes('/export?'))return new Response('synthetic export');
 else if(init?.method==='PATCH'){if(opts.editFailure){status=422;data={error:{code:'VALIDATION_ERROR',diagnostic:{category:'PRODUCT_VALIDATION_FAILED'}}};}else{const body=JSON.parse(String(init.body));current={...current,questions:current.questions.map((q,i)=>({...q,...body.questions[i]})),revision:1,professor_edited:true};data=current;}}
 else if(init?.method==='DELETE')data={status:'discarded'};
 return new Response(JSON.stringify(data),{status});});return {client:new APIClient(transport),transport};}
function mount(opts:Parameters<typeof api>[0]={}){const a=api(opts);const view=render(<AuthProvider api={a.client}><AssessmentPage/></AuthProvider>);return {...a,...view};}
beforeEach(()=>{nav.params=new URLSearchParams();Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:function(){this.setAttribute('open','');}});Object.defineProperty(HTMLDialogElement.prototype,'close',{configurable:true,value:function(){this.removeAttribute('open');}});});
async function generate(){await screen.findByRole('button',{name:'Generate assessment'});await userEvent.click(screen.getByRole('button',{name:'Generate assessment'}));}
it('requires authorized material and offers upload',async()=>{mount({empty:true});await screen.findByText('Academic material is required');expect(screen.getByRole('link',{name:'Upload material'})).toHaveAttribute('href','/library/upload');});
it('accepts course and material handoff without printing IDs',async()=>{nav.params=new URLSearchParams({material:material.material_id});mount();await screen.findByLabelText(material.filename);expect(screen.getByLabelText(material.filename)).toBeChecked();expect(screen.queryByText(material.material_id)).not.toBeInTheDocument();});
it('does not substitute a guessed unavailable material',async()=>{nav.params=new URLSearchParams({material:'unknown'});mount();await screen.findByRole('button',{name:'Generate assessment'});expect(screen.getByRole('button',{name:'Generate assessment'})).toBeDisabled();});
it('shows supported modes, distributions and deterministic marks',async()=>{const {transport}=mount();await screen.findByLabelText('Question Paper');await userEvent.click(screen.getByLabelText('Question Paper'));await generate();await screen.findByRole('heading',{name:'Review: Synthetic Assessment'});const call=transport.mock.calls.find(([p])=>String(p).endsWith('/generate'));expect(JSON.parse(String(call?.[1]?.body))).toMatchObject({assessment_type:'Question Paper',total_questions:2,total_marks:2,course:'C',subject:'ML'});});
it('blocks incoherent configuration totals',async()=>{mount();await screen.findByLabelText('Easy count');await userEvent.clear(screen.getByLabelText('Easy count'));await userEvent.type(screen.getByLabelText('Easy count'),'1');expect(screen.getByRole('button',{name:'Generate assessment'})).toBeDisabled();});
it('submits PYQ as multipart then passes only its session handle',async()=>{const {transport}=mount();await screen.findByLabelText('Optional PYQ style guidance');await userEvent.upload(screen.getByLabelText('Optional PYQ style guidance'),new File(['synthetic'],'style.pdf',{type:'application/pdf'}));await generate();await screen.findByRole('heading',{name:'Review: Synthetic Assessment'});expect(transport.mock.calls.find(([p])=>String(p).endsWith('/pyq'))?.[1]?.body).toBeInstanceOf(FormData);expect(JSON.parse(String(transport.mock.calls.find(([p])=>String(p).endsWith('/generate'))?.[1]?.body))).toMatchObject({pyq_handle:'private-pyq'});expect(screen.queryByText('private-pyq')).not.toBeInTheDocument();});
it('shows truthful pending state and browser-only cancellation',async()=>{mount({pending:true});await generate();await screen.findByRole('button',{name:'Stop waiting'});await userEvent.click(screen.getByRole('button',{name:'Stop waiting'}));await screen.findByText(/Server inference may still finish/);expect(screen.queryByRole('heading',{name:'Review: Synthetic Assessment'})).not.toBeInTheDocument();});
it.each(['INSUFFICIENT_EVIDENCE','PROVIDER_ERROR','TIMEOUT','INVALID_JSON','SCHEMA_INVALID','PRODUCT_VALIDATION_FAILED'])('maps %s safely without rejected output',async(category)=>{mount({status:422,category});await generate();await screen.findByRole('alert');expect(screen.queryByText(/RAW PRIVATE/)).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Export PDF'})).not.toBeInTheDocument();});
it.each([401,403])('handles HTTP %s without a valid workspace',async(status)=>{mount({status});await generate();await screen.findByRole('alert');expect(screen.queryByRole('heading',{name:'Review: Synthetic Assessment'})).not.toBeInTheDocument();});
it('reviews canonical MCQ options and explicit answer key without another generation',async()=>{const {transport}=mount();await generate();await screen.findByLabelText('Question 1 option A');expect(screen.getByLabelText('Question 1 option A')).toHaveValue('Projection');expect(screen.queryByLabelText('Question 1 correct answer')).not.toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Answer Key / Review'}));expect(screen.getByLabelText('Question 1 correct answer')).toHaveValue('A');expect(screen.getByLabelText('Question 1 reference answer')).toHaveValue('A synthetic reference answer.');expect(transport.mock.calls.filter(([p])=>String(p).endsWith('/generate'))).toHaveLength(1);});
it('tracks dirty edits, disables export and revalidates explicit fields with CSRF',async()=>{const {transport}=mount();await generate();await screen.findByLabelText('Question 1 text');await userEvent.type(screen.getByLabelText('Question 1 text'),' Professor addition');expect(screen.getByRole('button',{name:'Export PDF'})).toBeDisabled();await userEvent.click(screen.getByRole('button',{name:'Validate professor edits'}));await screen.findByText(/Professor edits validated. Review academic/);expect(screen.getByRole('button',{name:'Export PDF'})).toBeEnabled();const call=transport.mock.calls.find(([,init])=>init?.method==='PATCH');expect(call?.[1]?.headers).toMatchObject({'X-CSRF-Token':'synthetic-csrf'});expect(JSON.parse(String(call?.[1]?.body)).questions[0]).not.toHaveProperty('evidence_ids');});
it('keeps invalid local edits unexportable and warns about marks mismatch',async()=>{mount({editFailure:true});await generate();await screen.findByLabelText('Question 1 marks');fireEvent.change(screen.getByLabelText('Question 1 marks'),{target:{value:'5'}});await screen.findByText('Current marks do not match the configured target.');await userEvent.click(screen.getByRole('button',{name:'Validate professor edits'}));await screen.findByText(/Assessment requirements were not satisfied/);expect(screen.getByRole('button',{name:'Export PDF'})).toBeDisabled();});
it('requires confirmation before discarding dirty edits',async()=>{const {transport}=mount();await generate();await screen.findByLabelText('Question 1 text');await userEvent.type(screen.getByLabelText('Question 1 text'),' changed');await userEvent.click(screen.getByRole('button',{name:'New assessment'}));expect(screen.getByRole('dialog')).toHaveAccessibleName('Discard your assessment edits?');expect(transport.mock.calls.some(([,init])=>init?.method==='DELETE')).toBe(false);await userEvent.click(screen.getByRole('button',{name:'Discard and start new'}));await waitFor(()=>expect(screen.queryByRole('heading',{name:'Review: Synthetic Assessment'})).not.toBeInTheDocument());});
it.each(['PDF','DOCX'])('exports %s through the server with a safe filename',async(format)=>{const objectURL=vi.fn(()=> 'blob:synthetic');Object.defineProperty(URL,'createObjectURL',{configurable:true,value:objectURL});Object.defineProperty(URL,'revokeObjectURL',{configurable:true,value:vi.fn()});const click=vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});const {transport}=mount();await generate();await screen.findByRole('button',{name:`Export ${format}`});await userEvent.click(screen.getByRole('button',{name:`Export ${format}`}));await waitFor(()=>expect(objectURL).toHaveBeenCalled());expect(transport.mock.calls.some(([p])=>String(p).includes(`/export?format=${format.toLowerCase()}&answer_key=false`))).toBe(true);expect(click).toHaveBeenCalled();});
it('has accessible configuration and review controls',async()=>{const view=mount();await generate();await screen.findByLabelText('Question 1 text');const report=await axe.run(view.container,{rules:{'color-contrast':{enabled:false},region:{enabled:false}}});expect(report.violations.map(v=>v.id)).toEqual([]);});

it('loads protected assistant assessment handoff without regenerating or showing guessed configuration',async()=>{nav.params=new URLSearchParams({workspace:'private-workspace'});const {transport}=mount();await screen.findByLabelText('Question 1 text');expect(screen.queryByText('Configure assessment')).not.toBeInTheDocument();expect(transport.mock.calls.some(([p])=>String(p).endsWith('/generate'))).toBe(false);});
