import React from 'react';
import {beforeEach,it,expect,vi} from 'vitest';
import {render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import axe from 'axe-core';
import {APIClient} from '@/lib/api';
import {AuthProvider} from '@/features/auth';
import {ProtectedShell} from '@/components/shell';
import {AssistantPage} from '@/features/assistant';
import type {PlanAction,Outcome} from '@/types/assistant';
const nav=vi.hoisted(()=>({push:vi.fn(),replace:vi.fn()}));
vi.mock('next/navigation',()=>({usePathname:()=>'/assistant',useRouter:()=>nav}));
vi.mock('next/link',()=>({default:({href,children,...p}:{href:string}&React.ComponentProps<'a'>)=><a href={href} {...p}>{children}</a>}));
const navigate:PlanAction={action_id:'internal_step',action_type:'NAVIGATE',parameters:{page:'Professor Dashboard'},depends_on:[]};
function outcome(a:PlanAction,status:Outcome['status']='completed'):Outcome{return {action_id:a.action_id,status,type:a.action_type,summary:status==='completed'?'Completed; professor review required.':'Failed.',destination:a.action_type==='CREATE_DOCUMENT'?'/documents':a.action_type==='CREATE_ASSESSMENT'?'/assessment':'/home',answer:null,grounded:null,sources:[],student_count:null};}
type Options={actions?:PlanAction[];unsupported?:boolean;clarification?:boolean;plannerError?:string;plannerStatus?:number;pending?:boolean;executionPending?:boolean;executionError?:number;partial?:boolean;datasets?:boolean;student?:boolean;knowledge?:boolean;noEvidence?:boolean;csrf?:boolean};
function api(o:Options={}){const actions=o.actions??[navigate];let executed=false;let retried=false;let csrf=false;
const transport=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const path=String(input);const b=init?.body?JSON.parse(String(init.body)):{};let data:unknown={};let status=200;
if(path.endsWith('/auth/me'))data={professor_id:'synthetic',display_name:'Synthetic Professor',institution_id:'synthetic',department_id:'synthetic'};
else if(path.endsWith('/auth/csrf'))data={csrf_token:'synthetic-csrf'};
else if(path.endsWith('/students/workspaces'))data=o.datasets?[{handle:'private-dataset'}]:[];
else if(path.endsWith('/assistant/plan')){if(o.csrf&&!csrf){csrf=true;return new Response(JSON.stringify({error:{code:'CSRF_REJECTED'}}),{status:403});}if(o.pending)return new Promise<Response>((_,reject)=>init?.signal?.addEventListener('abort',()=>reject(new DOMException('Stopped','AbortError'))));status=o.plannerStatus??(o.plannerError?422:200);data=status===200?{handle:'server-plan',actions:o.unsupported?[]:actions,unsupported:!!o.unsupported}:{error:{code:o.plannerError==='UNSUPPORTED_OPERATION'?'UNSUPPORTED_OPERATION':'VALIDATION_ERROR',diagnostic:{category:o.plannerError},message:'RAW PRIVATE /path invalid JSON'}};}
else if(path.endsWith('/preview'))data={handle:'server-plan',actions:o.unsupported?[]:actions,unsupported:!!o.unsupported,valid:!o.unsupported&&!o.clarification,clarifications:o.clarification?[{action_id:actions[0].action_id,missing_fields:['scope.course','scope.units']}]:[]};
else if(path.endsWith('/execute')){if(o.executionPending)return new Promise<Response>((_,reject)=>init?.signal?.addEventListener('abort',()=>reject(new DOMException('Stopped','AbortError'))));status=o.executionError??200;executed=true;retried=!!b.retry;data={status:'completed'};}
else if(path.endsWith('/results')){if(!executed)status=404;let rows=actions.map((a,i)=>outcome(a,o.partial&&!retried&&i===0?'failed':'completed'));if(o.student)rows=[{...outcome(actions[0]),type:'ANALYZE_STUDENTS',student_count:2,destination:'/students'}];if(o.knowledge)rows=[{...outcome(actions[0]),type:'ASK_KNOWLEDGE',answer:o.noEvidence?'No matching material.':'Synthetic grounded answer.',grounded:!o.noEvidence,sources:o.noEvidence?[]:['Synthetic notes'],destination:'/knowledge'}];data={status:o.partial&&!retried?'partial_failure':'completed',results:rows};}
else if(path.endsWith('/handoff'))data={handle:'protected-artifact',destination:b.destination};
else if(init?.method==='DELETE')data={status:'discarded'};
if(status!==200&&path.endsWith('/execute'))data={error:{code:'ACCESS_DENIED',message:'RAW PRIVATE'}};
return new Response(JSON.stringify(data),{status});});return {client:new APIClient(transport),transport};}
function mount(o:Options={},shell=false){const a=api(o);return {...a,...render(<AuthProvider api={a.client}>{shell?<ProtectedShell><AssistantPage/></ProtectedShell>:<AssistantPage/>}</AuthProvider>)};}
async function plan(){await screen.findByLabelText('Professor request');await userEvent.type(screen.getByLabelText('Professor request'),'Open my workspace');await userEvent.click(screen.getByRole('button',{name:'Review plan'}));}
async function ready(){await plan();await screen.findByRole('heading',{name:'Plan validated'});await waitFor(()=>expect(screen.getByRole('region',{name:'Plan preview'})).toHaveFocus());}
async function execute(){await userEvent.click(screen.getByLabelText('I approve this exact plan for execution.'));await userEvent.click(screen.getByRole('button',{name:'Execute approved plan'}));await screen.findByRole('region',{name:'Execution results'});}
beforeEach(()=>{nav.push.mockReset();nav.replace.mockReset();});
it('activates assistant and Activity sidebar routes',async()=>{mount({},true);await screen.findByRole('link',{name:'Smart Assistant'});expect(screen.getByRole('link',{name:'Smart Assistant'})).toHaveAttribute('href','/assistant');expect(screen.getByRole('link',{name:'Activity'})).toHaveAttribute('href','/activity');expect(screen.queryByText('Upcoming')).not.toBeInTheDocument();});
it('shows session-only controlled orchestration without fake history',async()=>{mount();await screen.findByLabelText('Professor request');expect(screen.getByText(/No persistent conversation history/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Execute approved plan'})).not.toBeInTheDocument();});
it('starter requests populate input without auto planning',async()=>{const {transport}=mount();await userEvent.click(screen.getByRole('button',{name:'Draft a notice for a seminar.'}));expect(screen.getByLabelText('Professor request')).toHaveValue('Draft a notice for a seminar.');expect(transport.mock.calls.some(([p])=>String(p).endsWith('/assistant/plan'))).toBe(false);});
it('sends request to server without client executable actions',async()=>{const {transport}=mount();await ready();const b=JSON.parse(String(transport.mock.calls.find(([p])=>String(p).endsWith('/assistant/plan'))?.[1]?.body));expect(b).toEqual({request:'Open my workspace',student_handle:null});});
it('shows loading and honest stop waiting',async()=>{mount({pending:true});await plan();await screen.findByText('Planning and validating request…');await userEvent.click(screen.getByRole('button',{name:'Stop waiting'}));await screen.findByText(/Backend inference\/execution was not cancelled/);});
it('focuses validated preview without internal action IDs',async()=>{mount();await ready();await waitFor(()=>expect(screen.getByRole('region',{name:'Plan preview'})).toHaveFocus());expect(screen.queryByText('internal_step')).not.toBeInTheDocument();});
it('requires explicit approval and uses CSRF',async()=>{const {transport}=mount();await ready();expect(screen.getByRole('button',{name:'Execute approved plan'})).toBeDisabled();expect(transport.mock.calls.some(([p])=>String(p).endsWith('/execute'))).toBe(false);await execute();const call=transport.mock.calls.find(([p])=>String(p).endsWith('/execute'));expect(JSON.parse(String(call?.[1]?.body))).toEqual({confirmed:true,retry:false});expect(call?.[1]?.headers).toMatchObject({'X-CSRF-Token':'synthetic-csrf'});});
it('displays multi-action dependency without invented chain support',async()=>{mount({actions:[{action_id:'quiz',action_type:'CREATE_ASSESSMENT',parameters:{scope:{course:'Synthetic course',units:['Unit 3']}},depends_on:[]},{action_id:'notice',action_type:'CREATE_DOCUMENT',parameters:{document_type:'notice'},depends_on:['quiz']}]});await ready();expect(screen.getByText('Requires completion of step 1.')).toBeInTheDocument();expect(screen.getByText(/Synthetic course → Unit 3/)).toBeInTheDocument();});
it('shows safe clarification and blocks execution',async()=>{mount({clarification:true});await plan();await screen.findByRole('heading',{name:'Clarification required'});expect(screen.getByText(/Provide: Course, Units/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Execute approved plan'})).not.toBeInTheDocument();});
it('shows refusal without execution',async()=>{mount({unsupported:true});await plan();await screen.findByRole('heading',{name:'Unsupported request'});expect(screen.queryByRole('button',{name:'Execute approved plan'})).not.toBeInTheDocument();});
it.each(['INVALID_JSON','SCHEMA_INVALID','PRODUCT_VALIDATION_FAILED','PROVIDER_ERROR','TIMEOUT','INSUFFICIENT_EVIDENCE','UNSUPPORTED_OPERATION'])('safe planner failure %s',async(plannerError)=>{mount({plannerError});await plan();await screen.findByRole('alert');expect(screen.queryByText(/RAW PRIVATE/)).not.toBeInTheDocument();expect(screen.queryByRole('region',{name:'Plan preview'})).not.toBeInTheDocument();});
it.each([401,403])('planner HTTP %s',async(plannerStatus)=>{mount({plannerStatus},true);await plan();if(plannerStatus===401)await screen.findByText(/Sign in to access/);else await screen.findByRole('alert');expect(screen.queryByText(/RAW PRIVATE/)).not.toBeInTheDocument();});
it('retains partial failure and explicitly retries safe failed actions',async()=>{const {transport}=mount({actions:[navigate,{...navigate,action_id:'other'}],partial:true});await ready();await execute();expect(screen.getByRole('heading',{name:'Partial failure'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Retry failed actions'})).toBeDisabled();await userEvent.click(screen.getByLabelText('I approve retrying failed safe actions.'));await userEvent.click(screen.getByRole('button',{name:'Retry failed actions'}));await screen.findByRole('heading',{name:'Completed'});expect(JSON.parse(String(transport.mock.calls.filter(([p])=>String(p).endsWith('/execute')).at(-1)?.[1]?.body)).retry).toBe(true);});
it('does not execute stale requests',async()=>{mount();await ready();await userEvent.type(screen.getByLabelText('Professor request'),' changed');expect(screen.getByText(/Review a new plan before execution/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Execute approved plan'})).toBeDisabled();});
it('discards server plan explicitly',async()=>{const {transport}=mount();await ready();await userEvent.click(screen.getByRole('button',{name:'Discard plan'}));await screen.findByText(/Plan discarded/);expect(transport.mock.calls.some(([,i])=>i?.method==='DELETE')).toBe(true);expect(screen.queryByRole('region',{name:'Plan preview'})).not.toBeInTheDocument();});
it('student attachment contains a handle only and results contain counts only',async()=>{const {transport}=mount({datasets:true,student:true,actions:[{action_id:'students',action_type:'ANALYZE_STUDENTS',parameters:{view:'Concern'},depends_on:[]}]});await screen.findByRole('option',{name:'Temporary dataset 1'});await userEvent.selectOptions(screen.getByLabelText('Temporary student dataset (optional)'),'private-dataset');await ready();await execute();expect(screen.getByText(/2 students in the requested local view/)).toBeInTheDocument();expect(screen.getByRole('link',{name:'Open in Student Analytics'})).toHaveAttribute('href','/students?workspace=private-dataset&view=Concern');expect(JSON.parse(String(transport.mock.calls.find(([p])=>String(p).endsWith('/assistant/plan'))?.[1]?.body)).student_handle).toBe('private-dataset');});
it.each(['CREATE_ASSESSMENT','CREATE_DOCUMENT','ASK_KNOWLEDGE'] as const)('typed %s handoff uses only a protected handle in URL',async(action_type)=>{mount({actions:[{...navigate,action_type}],knowledge:action_type==='ASK_KNOWLEDGE'});await ready();await execute();const studio=action_type==='CREATE_ASSESSMENT'?'Assessment Studio':action_type==='CREATE_DOCUMENT'?'Document Studio':'Knowledge';await userEvent.click(screen.getByRole('button',{name:`Open in ${studio}`}));await waitFor(()=>expect(nav.push).toHaveBeenCalledWith(`${action_type==='CREATE_ASSESSMENT'?'/assessment':action_type==='CREATE_DOCUMENT'?'/documents':'/knowledge'}?workspace=protected-artifact`));});
it.each([false,true])('knowledge result no evidence=%s',async(noEvidence)=>{mount({knowledge:true,noEvidence});await ready();await execute();expect(screen.getByText(noEvidence?'Insufficient matching material':'Grounded answer available')).toBeInTheDocument();expect(screen.queryByText('Synthetic notes')!==null).toBe(!noEvidence);});
it('execution authorization failure blocks blind retry',async()=>{mount({executionError:403});await ready();await userEvent.click(screen.getByLabelText('I approve this exact plan for execution.'));await userEvent.click(screen.getByRole('button',{name:'Execute approved plan'}));await screen.findByRole('alert');expect(screen.getByRole('button',{name:'Execute approved plan'})).toBeDisabled();expect(screen.getByRole('button',{name:'Check execution results'})).toBeInTheDocument();});
it('stop execution waiting marks state uncertain',async()=>{mount({executionPending:true});await ready();await userEvent.click(screen.getByLabelText('I approve this exact plan for execution.'));await userEvent.click(screen.getByRole('button',{name:'Execute approved plan'}));await screen.findByText('Executing confirmed plan…');await userEvent.click(screen.getByRole('button',{name:'Stop waiting'}));expect(screen.getByRole('button',{name:'Execute approved plan'})).toBeDisabled();});
it('retries only CSRF rejection before planning',async()=>{const {transport}=mount({csrf:true});await ready();expect(transport.mock.calls.filter(([p])=>String(p).endsWith('/assistant/plan'))).toHaveLength(2);});
it('has accessible request, plan and confirmation controls',async()=>{const {container}=mount();await ready();const result=await axe.run(container,{rules:{'color-contrast':{enabled:false},region:{enabled:false}}});expect(result.violations).toEqual([]);});
it('uses no browser persistent storage',async()=>{const spy=vi.spyOn(Storage.prototype,'setItem');mount();await ready();await execute();expect(spy).not.toHaveBeenCalled();});
