import React from 'react';
import {beforeEach,it,expect,vi} from 'vitest';
import {render,screen,waitFor,fireEvent,within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import axe from 'axe-core';
import {APIClient} from '@/lib/api';
import {AuthProvider} from '@/features/auth';
import {ProtectedShell} from '@/components/shell';
import {DocumentStudioPage} from '@/features/documents';
import type {StudioDocument,DocumentCatalog} from '@/types/api';
const nav=vi.hoisted(()=>({params:new URLSearchParams()}));
vi.mock('next/navigation',()=>({useSearchParams:()=>nav.params,usePathname:()=>'/documents',useRouter:()=>({replace:vi.fn()})}));
vi.mock('next/link',()=>({default:({href,children,...p}:{href:string}&React.ComponentProps<'a'>)=><a href={href} {...p}>{children}</a>}));
const catalog:DocumentCatalog={types:[{value:'notice',label:'Notice',style:'announcement'},{value:'official_letter',label:'Official Letter',style:'letter'},{value:'memo',label:'Memo',style:'memo'}],tones:['Formal & Natural','Concise Official'],fields:['title','recipient','sender','date','reference_number','subject','salutation','closing','signature'],fact_fields:['date','reference_number','recipient','sender','title','subject','signature','body'],preference_scopes:['document_type','general','template'],preference_categories:['tone_style','structural','formatting','wording']};
const original:StudioDocument={handle:'opaque-workspace',document_id:null,document_type:'notice',title:'Synthetic Notice',recipient:'Synthetic students',sender:'Synthetic department',date:'14 October 2026',reference_number:'SYN/1',subject:'Tutorial',salutation:'',body:['Synthetic tutorial. Budget 2500.'],closing:'',signature:'Synthetic professor',version_count:1,saved:false,status:null,versions:[{version_number:1,source:'generated',created_at:'2026-10-05T10:00:00Z'}],facts:[{fact_id:'opaque-date',field:'date',value:'14 October 2026',source:'structured_request'}],provenance:{generation_type:'document',generated_at:'2026-10-05T10:00:00Z',validation_status:'Validated',attempts_used:1,provider:'ollama',model:'qwen2.5:3b',grounded:false,professor_edited:false,preferences_applied:false}};
type Options={saved?:boolean;generationError?:string;generationStatus?:number;pending?:boolean;refineError?:boolean;refinePending?:boolean;exportError?:boolean;listError?:number;saveFailure?:boolean};
function api(options:Options={}){
 let current=structuredClone(original);let persisted=options.saved;let prefs:{preference_id:string;instruction:string;category:string;scope:string;active:boolean;approved:boolean;document_type:string|null;template_id:string|null;tone:string|null}[]=[];
 const append=(source:string)=>{current={...current,saved:false,version_count:current.version_count+1,versions:[...current.versions,{version_number:current.version_count+1,source,created_at:'2026-10-05T11:00:00Z'}]};};
 const transport=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const path=String(input);const body=init?.body?JSON.parse(String(init.body)):{};let status=200;let data:unknown={};
 if(path.endsWith('/auth/me'))data={professor_id:'synthetic',display_name:'Synthetic Professor',institution_id:'institute',department_id:'department'};
 else if(path.endsWith('/auth/csrf'))data={csrf_token:'synthetic-csrf'};
 else if(path.endsWith('/documents/catalog'))data=catalog;
 else if(path.endsWith('/documents')){status=options.listError??200;data=persisted?[{document_id:'saved-document',template_id:'standard_academic',title:'Synthetic Notice',document_type:'notice',version_count:current.version_count,status:'Draft',created_at:'2026-10-05',updated_at:'2026-10-05'}]:[];}
 else if(path.endsWith('/documents/generate')){if(options.pending)return new Promise<Response>((_,reject)=>init?.signal?.addEventListener('abort',()=>reject(new DOMException('Stopped','AbortError'))));if(options.generationError||options.generationStatus){status=options.generationStatus??422;data={error:{code:'VALIDATION_ERROR',diagnostic:{category:options.generationError,professor_message:'RAW PRIVATE /secret rejected content'}}};}else{current={...current,document_type:body.document_type};data=current;}}
 else if(path.endsWith('/documents/saved-document')){current={...current,document_id:'saved-document',saved:true,status:'Draft'};data=current;}
 else if(path.includes('/diff?'))data=[{field:'body[0:1]',action:'changed',before:original.body,after:current.body}];
 else if(path.endsWith('/conflicts'))data=current.facts;
 else if(path.endsWith('/resolve-edit')){if(body.update_confirmed){current={...current,...body.draft,facts:current.facts.map(f=>({...f,value:body.draft.date,source:'professor_confirmed'}))};append('professor_edit');}data=current;}
 else if(path.endsWith('/save')&&options.saveFailure){status=503;data={error:{code:'STORAGE_ERROR',diagnostic:{category:'PRODUCT_VALIDATION_FAILED'}}};}
 else if(path.endsWith('/save')){current={...current,document_id:'saved-document',saved:true,status:body.status};persisted=true;data=current;}
 else if(path.endsWith('/refine')){if(options.refinePending)return new Promise<Response>((_,reject)=>init?.signal?.addEventListener('abort',()=>reject(new DOMException('Stopped','AbortError'))));if(options.refineError){status=422;data={error:{code:'VALIDATION_ERROR',diagnostic:{category:'FACT_PRESERVATION_FAILED'}}};}else{current={...current,body:['Refined synthetic tutorial. Budget 2500.']};append('ai_refinement');data=current;}}
 else if(path.endsWith('/restore')){current={...current,body:[...original.body],date:original.date};append('restored');data=current;}
 else if(path.endsWith('/facts')){if(body.operation==='add')current={...current,facts:[...current.facts,{fact_id:'opaque-added',field:body.field,value:body.value,source:'professor_confirmed'}]};if(body.operation==='update')current={...current,facts:current.facts.map(f=>f.fact_id===body.fact_id?{...f,value:body.value}:f)};if(body.operation==='remove')current={...current,facts:current.facts.filter(f=>f.fact_id!==body.fact_id)};append('professor_edit');data={status:'updated'};}
 else if(path.endsWith('/feedback'))data={status:'saved'};
 else if(path.includes('/export?')){if(options.exportError){status=422;data={error:{code:'PDF_FONT_UNAVAILABLE',message:'RAW /private/font'}};}else return new Response('Synthetic export');}
 else if(path.endsWith('/preferences')){if(init?.method==='POST'){prefs=[{...body,preference_id:'own-preference',approved:true,active:true}];data={handle:'own-preference'};}else data=prefs;}
 else if(path.includes('/preferences/')){if(init?.method==='DELETE')prefs=[];else prefs=prefs.map(p=>({...p,...body}));data={status:'updated'};}
 else if(init?.method==='PATCH'){if(body.date!==current.date){status=409;data={error:{code:'CONFLICT'}};}else{current={...current,...body};append('professor_edit');data=current;}}
 else if(init?.method==='DELETE')data={status:'discarded'};
 else if(path.includes('/document-workspaces/'))data=current;
 return new Response(JSON.stringify(data),{status});
 });return {client:new APIClient(transport),transport};
}
function mount(options:Options={}){const a=api(options);return {...a,...render(<AuthProvider api={a.client}><DocumentStudioPage/></AuthProvider>)};}
beforeEach(()=>{nav.params=new URLSearchParams();Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:function(){this.setAttribute('open','');}});Object.defineProperty(HTMLDialogElement.prototype,'close',{configurable:true,value:function(){this.removeAttribute('open');}});});
async function generate(){await screen.findByLabelText('Purpose / drafting instructions');await userEvent.type(screen.getByLabelText('Purpose / drafting instructions'),'Draft a synthetic tutorial notice.');await userEvent.click(screen.getByRole('button',{name:'Generate document'}));}
async function ready(){await generate();await screen.findByLabelText('Document body (blank lines separate paragraphs)');}
async function refine(){await userEvent.type(screen.getByLabelText('Refinement instruction'),'Make concise');await userEvent.click(screen.getByRole('button',{name:'Refine current document'}));}
it('shows an honest empty list and authoritative catalog choices',async()=>{mount();await screen.findByText('Create your first academic or administrative document');expect(within(screen.getByLabelText('Document type')).getByRole('option',{name:'Official Letter'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Generate document'})).toBeDisabled();});
it('submits structured type, tone and facts without uncontracted fields',async()=>{const {transport}=mount();await screen.findByLabelText('Document type');await userEvent.selectOptions(screen.getByLabelText('Document type'),'official_letter');await userEvent.type(screen.getByLabelText('Date (optional)'),'14 October 2026');await ready();const body=JSON.parse(String(transport.mock.calls.find(([p])=>String(p).endsWith('/generate'))?.[1]?.body));expect(body).toMatchObject({document_type:'official_letter',date:'14 October 2026',template_id:'standard_academic'});expect(body).not.toHaveProperty('budget');expect(screen.getByLabelText('Edit salutation')).toBeInTheDocument();});
it('shows synchronous loading and honest browser-only cancellation',async()=>{mount({pending:true});await generate();await screen.findByText('Generating and validating document…');await userEvent.click(screen.getByRole('button',{name:'Stop waiting'}));await screen.findByText(/backend inference was not cancelled/);expect(screen.queryByLabelText('Document body (blank lines separate paragraphs)')).not.toBeInTheDocument();});
it('shows validation, confirmed facts and unsaved distinction',async()=>{mount();await ready();expect(screen.getByText('Validated structure')).toBeInTheDocument();expect(screen.getByText('Date: 14 October 2026')).toBeInTheDocument();expect(screen.getByText(/Unsaved changes \/ session version/)).toBeInTheDocument();expect(screen.queryByText('opaque-date')).not.toBeInTheDocument();expect(screen.queryByLabelText('Edit salutation')).not.toBeInTheDocument();});
it.each(['INVALID_JSON','SCHEMA_INVALID','PRODUCT_VALIDATION_FAILED','FACT_PRESERVATION_FAILED','PROVIDER_ERROR','TIMEOUT'])('safely presents %s without raw rejected output',async(generationError)=>{mount({generationError});await generate();await screen.findByRole('alert');expect(screen.queryByText(/RAW PRIVATE/)).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Export PDF'})).not.toBeInTheDocument();});
it.each([401,403])('handles generation HTTP %s',async(generationStatus)=>{mount({generationStatus});await generate();await screen.findByRole('alert');expect(screen.queryByLabelText('Document body (blank lines separate paragraphs)')).not.toBeInTheDocument();});
it('loads saved document handoff and actual title',async()=>{nav.params=new URLSearchParams({document:'saved-document'});mount({saved:true});await screen.findByLabelText('Document body (blank lines separate paragraphs)');expect(screen.getByRole('button',{name:'Open Synthetic Notice'})).toBeInTheDocument();expect(screen.getByText(/Saved privately/)).toBeInTheDocument();});
it('filters saved metadata',async()=>{mount({saved:true});await screen.findByLabelText('Find a saved document');await userEvent.type(screen.getByLabelText('Find a saved document'),'unmatched');expect(screen.getByText('No matching saved documents')).toBeInTheDocument();});
it('tracks local dirty edits and saves explicitly with CSRF before export',async()=>{const {transport}=mount();await ready();await userEvent.type(screen.getByLabelText('Document body (blank lines separate paragraphs)'),' Professor addition');expect(screen.getByRole('button',{name:'Export PDF'})).toBeDisabled();expect(transport.mock.calls.some(([,i])=>i?.method==='PATCH')).toBe(false);await userEvent.click(screen.getByRole('button',{name:'Save document'}));await screen.findByText(/Document and coherent version history saved privately/);expect(screen.getByRole('button',{name:'Export PDF'})).toBeEnabled();const call=transport.mock.calls.find(([,i])=>i?.method==='PATCH');expect(call?.[1]?.headers).toMatchObject({'X-CSRF-Token':'synthetic-csrf'});expect(JSON.parse(String(call?.[1]?.body))).not.toHaveProperty('facts');});
it('adds a fact and reloads authoritative metadata',async()=>{mount();await ready();await userEvent.selectOptions(screen.getByLabelText('Confirmed fact field'),'body');await userEvent.type(screen.getByLabelText('New confirmed fact value'),'2500');await userEvent.click(screen.getByRole('button',{name:'Add confirmed fact'}));await screen.findByText('Body: 2500');});
it('updates fact through explicit action',async()=>{mount();await ready();await userEvent.click(screen.getByRole('button',{name:'Update confirmed fact 1'}));await screen.findByText(/Confirmed fact change validated/);});
it('requires confirmation before fact removal',async()=>{mount();await ready();expect(screen.getByRole('button',{name:'Remove confirmed fact 1'})).toBeDisabled();await userEvent.click(screen.getByLabelText('Confirm removal of fact 1'));await userEvent.click(screen.getByRole('button',{name:'Remove confirmed fact 1'}));await screen.findByText('No confirmed fact constraints recorded.');});
it('detects conflict and explicitly updates facts without autosave',async()=>{const {transport}=mount();await ready();fireEvent.change(screen.getByLabelText('Edit date'),{target:{value:'16 October 2026'}});await userEvent.click(screen.getByRole('button',{name:'Save document'}));await screen.findByRole('heading',{name:'Confirmed fact conflict'});expect(screen.getByRole('button',{name:'Export PDF'})).toBeDisabled();await userEvent.click(screen.getByRole('button',{name:'Update confirmed facts and apply edit'}));await screen.findByText('Date: 16 October 2026');expect(transport.mock.calls.filter(([p])=>String(p).endsWith('/save'))).toHaveLength(0);});
it('keeps original facts without overwriting professor local content',async()=>{mount();await ready();fireEvent.change(screen.getByLabelText('Edit date'),{target:{value:'16 October 2026'}});await userEvent.click(screen.getByRole('button',{name:'Save document'}));await screen.findByRole('heading',{name:'Confirmed fact conflict'});await userEvent.click(screen.getByRole('button',{name:'Keep original confirmed facts and revise edit'}));await screen.findByText(/Original confirmed facts retained/);expect(screen.getByLabelText('Edit date')).toHaveValue('16 October 2026');expect(screen.getByText('Date: 14 October 2026')).toBeInTheDocument();});
it('retains displayed valid version on failed refinement',async()=>{mount({refineError:true});await ready();await refine();await screen.findByRole('alert');expect(screen.getByLabelText('Document body (blank lines separate paragraphs)')).toHaveValue(original.body[0]);expect(screen.getByText('Version 1',{selector:'strong'})).toBeInTheDocument();});
it('successful refinement adds history and preserves confirmed facts',async()=>{mount();await ready();await refine();await screen.findByDisplayValue('Refined synthetic tutorial. Budget 2500.');expect(screen.getByText('Version 2',{selector:'strong'})).toBeInTheDocument();expect(screen.getAllByText(/AI refinement/)[0]).toBeInTheDocument();expect(screen.getByText('Date: 14 October 2026')).toBeInTheDocument();});
it('blocks stale export after stopped refinement until server state reload',async()=>{mount({refinePending:true});await ready();await refine();await screen.findByRole('button',{name:'Stop waiting'});await userEvent.click(screen.getByRole('button',{name:'Stop waiting'}));expect(screen.getByRole('button',{name:'Export PDF'})).toBeDisabled();await userEvent.click(screen.getByRole('button',{name:'Reload current session version before continuing'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Export PDF'})).toBeEnabled());});
it('compares versions deterministically through API',async()=>{const {transport}=mount();await ready();await refine();await screen.findByText('Version 2',{selector:'strong'});await userEvent.click(screen.getByRole('button',{name:'Compare versions'}));await screen.findByRole('region',{name:'Version comparison'});expect(screen.getByText('Before')).toBeInTheDocument();expect(transport.mock.calls.some(([p])=>String(p).includes('/diff?before=0&after=1'))).toBe(true);});
it('restore requires confirmation and appends a new version',async()=>{const {transport}=mount();await ready();await refine();await screen.findByText('Version 2',{selector:'strong'});await userEvent.click(screen.getByRole('button',{name:'Restore version 1'}));expect(screen.getByRole('dialog')).toHaveAccessibleName('Restore this historical version?');expect(transport.mock.calls.some(([p])=>String(p).endsWith('/restore'))).toBe(false);await userEvent.click(screen.getByRole('button',{name:'Confirm restore'}));await screen.findByText('Version 3',{selector:'strong'});expect(screen.getByLabelText('Document body (blank lines separate paragraphs)')).toHaveValue(original.body[0]);});
it('warns before discarding unsaved document',async()=>{mount();await ready();await userEvent.click(screen.getByRole('button',{name:'New document'}));expect(screen.getByRole('dialog')).toHaveAccessibleName('Discard unsaved document changes?');await userEvent.click(screen.getByRole('button',{name:'Keep working'}));expect(screen.getByLabelText('Document body (blank lines separate paragraphs)')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'New document'}));await userEvent.click(screen.getByRole('button',{name:'Discard and continue'}));await screen.findByRole('button',{name:'Generate document'});});
it('feedback requires saved current version and does not auto-learn',async()=>{const {transport}=mount();await ready();expect(screen.getByRole('button',{name:'Save feedback'})).toBeDisabled();await userEvent.click(screen.getByRole('button',{name:'Save document'}));await screen.findByText(/Document and coherent version history saved privately/);await userEvent.type(screen.getByLabelText('Private feedback note (optional)'),'Synthetic feedback');await userEvent.click(screen.getByRole('button',{name:'Save feedback'}));await screen.findByText(/No preference was learned automatically/);expect(transport.mock.calls.some(([p,i])=>String(p).endsWith('/preferences')&&i?.method==='POST')).toBe(false);});
async function approve(){await screen.findByText('Professor-approved preferences');await userEvent.click(screen.getByText('Professor-approved preferences'));await userEvent.type(screen.getByLabelText('Reusable style instruction'),'Use concise paragraphs.');expect(screen.getByRole('button',{name:'Approve preference'})).toBeDisabled();await userEvent.click(screen.getByLabelText('I approve this as reusable style guidance, not document facts'));await userEvent.click(screen.getByRole('button',{name:'Approve preference'}));await screen.findByRole('button',{name:'Deactivate preference'});}
it('requires explicit preference approval and displays only returned private data',async()=>{const {transport}=mount();await approve();expect(screen.getByText(/Approved · Active/)).toBeInTheDocument();const call=transport.mock.calls.find(([p,i])=>String(p).endsWith('/preferences')&&i?.method==='POST');expect(JSON.parse(String(call?.[1]?.body))).toMatchObject({scope:'document_type',document_type:'notice'});expect(screen.queryByText('own-preference')).not.toBeInTheDocument();});
it('allows preference deactivation and confirmed deletion',async()=>{mount();await approve();await userEvent.click(screen.getByRole('button',{name:'Deactivate preference'}));await screen.findByRole('button',{name:'Activate preference'});expect(screen.getByRole('button',{name:'Delete preference'})).toBeDisabled();await userEvent.click(screen.getByLabelText('Confirm preference deletion'));await userEvent.click(screen.getByRole('button',{name:'Delete preference'}));await screen.findByText('No approved preferences yet.');});
it('shows safe provenance without hidden response internals',async()=>{mount();await ready();await userEvent.click(screen.getByText('Generation provenance'));expect(screen.getByText('qwen2.5:3b')).toBeInTheDocument();expect(screen.getByText('Preferences applied')).toBeInTheDocument();expect(screen.queryByText(/base_url|system_prompt|response_hash/)).not.toBeInTheDocument();});
it.each(['PDF','DOCX'])('exports %s through server-owned current version',async(format)=>{const objectURL=vi.fn(()=> 'blob:synthetic');Object.defineProperty(URL,'createObjectURL',{configurable:true,value:objectURL});Object.defineProperty(URL,'revokeObjectURL',{configurable:true,value:vi.fn()});vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});const {transport}=mount();await ready();await userEvent.click(screen.getByRole('button',{name:`Export ${format}`}));await screen.findByText(/Download prepared from the current validated/);expect(objectURL).toHaveBeenCalled();expect(transport.mock.calls.some(([p])=>String(p).includes(`/export?format=${format.toLowerCase()}`))).toBe(true);});
it('shows safe actionable font error',async()=>{mount({exportError:true});await ready();await userEvent.click(screen.getByRole('button',{name:'Export PDF'}));await screen.findByText(/Ask the administrator to configure it, or export DOCX/);expect(screen.queryByText(/RAW \/private/)).not.toBeInTheDocument();});
it.each([401,403])('handles list HTTP %s without private editor',async(listError)=>{mount({listError});await screen.findByRole('alert');expect(screen.queryByLabelText('Document type')).not.toBeInTheDocument();});
it('has accessible editor, facts and history controls',async()=>{const view=mount();await ready();const result=await axe.run(view.container,{rules:{'color-contrast':{enabled:false},region:{enabled:false}}});expect(result.violations.map(v=>v.id)).toEqual([]);});

it('activates Document Studio and Student Analytics with active assistant workflow',async()=>{render(<AuthProvider api={api().client}><ProtectedShell><p>Synthetic private workspace</p></ProtectedShell></AuthProvider>);await screen.findByText('Synthetic private workspace');expect(screen.getAllByRole('link',{name:'Document Studio'})[0]).toHaveAttribute('href','/documents');expect(screen.getAllByRole('link',{name:'Assessment Studio'})[0]).toHaveAttribute('href','/assessment');expect(screen.getAllByRole('link',{name:'Student Analytics'})[0]).toHaveAttribute('href','/students');expect(screen.getAllByRole('link',{name:'Smart Assistant'})[0]).toHaveAttribute('href','/assistant');});
it('explicit preference update uses CSRF and only approved local instruction',async()=>{const {transport}=mount();await approve();await userEvent.clear(screen.getByLabelText('Approved instruction'));await userEvent.type(screen.getByLabelText('Approved instruction'),'Use shorter paragraphs.');await userEvent.click(screen.getByRole('button',{name:'Update preference'}));await screen.findByDisplayValue('Use shorter paragraphs.');const call=transport.mock.calls.find(([p,i])=>String(p).includes('/preferences/')&&i?.method==='PATCH');expect(call?.[1]?.headers).toMatchObject({'X-CSRF-Token':'synthetic-csrf'});});
it('warns before switching away from dirty document to another saved record',async()=>{mount({saved:true});await ready();await userEvent.type(screen.getByLabelText('Document body (blank lines separate paragraphs)'),' Unsaved');await userEvent.click(screen.getByRole('button',{name:'Open Synthetic Notice'}));expect(screen.getByRole('dialog')).toHaveAccessibleName('Discard unsaved document changes?');});

it('loads saved handoff under StrictMode without leaving a cancelled first request stuck',async()=>{nav.params=new URLSearchParams({document:'saved-document'});render(<React.StrictMode><AuthProvider api={api({saved:true}).client}><DocumentStudioPage/></AuthProvider></React.StrictMode>);await screen.findByLabelText('Document body (blank lines separate paragraphs)');expect(screen.getByText(/Saved privately/)).toBeInTheDocument();});

it('reports persistence failure distinctly and keeps applied edits marked unsaved',async()=>{mount({saveFailure:true});await ready();await userEvent.type(screen.getByLabelText('Document body (blank lines separate paragraphs)'),' Professor addition');await userEvent.click(screen.getByRole('button',{name:'Save document'}));await screen.findByText(/Local storage could not complete this operation/);expect(screen.getByLabelText('Document body (blank lines separate paragraphs)')).toHaveValue(original.body[0]+' Professor addition');expect(screen.getByText('Version 2',{selector:'strong'})).toBeInTheDocument();expect(screen.getByText(/Unsaved changes \/ session version/)).toBeInTheDocument();expect(screen.queryByText(/history saved privately/)).not.toBeInTheDocument();});

it('loads an unsaved assistant handoff in the full Document Studio',async()=>{nav.params=new URLSearchParams({workspace:'opaque-workspace'});const {transport}=mount();await screen.findByLabelText('Document body (blank lines separate paragraphs)');expect(screen.getByText('Date: 14 October 2026')).toBeInTheDocument();expect(transport.mock.calls.some(([p])=>String(p).endsWith('/generate'))).toBe(false);});
