import React from 'react';
import { beforeEach,describe,it,expect,vi } from 'vitest';
import { render,screen,fireEvent } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import axe from 'axe-core';
import { APIClient } from '@/lib/api';
import { AuthProvider } from '@/features/auth';
import { CoursesPage } from '@/features/courses';
import { LibraryPage } from '@/features/library';
import { MaterialPage,UploadPage } from '@/features/materials';
import { KnowledgePage } from '@/features/knowledge';
import { decodeRouteSegment,normalizeHierarchy,projectCourses,scopeURL } from '@/lib/academic';
const nav=vi.hoisted(()=>({params:new URLSearchParams(),pathname:'/library',replace:vi.fn()}));
vi.mock('next/navigation',()=>({usePathname:()=>nav.pathname,useRouter:()=>({replace:nav.replace}),useSearchParams:()=>nav.params}));
vi.mock('next/link',()=>({default:({href,children,...p}:{href:string}&React.ComponentProps<'a'>)=><a href={href} {...p}>{children}</a>}));
const m={material_id:'synthetic-id',filename:'Synthetic PCA.pdf',course:'B.Tech CSE',semester:'Semester 7',subject:'Machine Learning',unit:'Unit 2',created_at:'2026-10-05T10:00:00Z',visibility:'PRIVATE',can_manage:true};
const other={...m,material_id:'other-id',filename:'Synthetic SVM.pdf',semester:'Semester 6',unit:'Unit 1'};
function fake(opts:{empty?:boolean;upload?:unknown;failure?:number;edit?:boolean;remove?:boolean;readOnly?:boolean;many?:boolean}={}){
 const fetcher=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const path=String(input);let data:unknown={};let status=200;
 if(path.endsWith('/auth/me'))data={professor_id:'prof',display_name:'Synthetic Professor',institution_id:'inst',department_id:'dept'};
 else if(path.endsWith('/auth/csrf'))data={csrf_token:'synthetic-csrf'};
 else if(path.endsWith('/materials')&&init?.method==='POST'){status=opts.failure??200;data=status===200?opts.upload??{success:true,duplicate:false,material:m}:{error:{code:'FAILURE',message:'/private/secret'}};}
 else if(path.endsWith('/materials'))data=opts.empty?[]:opts.many?Array.from({length:45},(_,i)=>({...m,material_id:`id-${i}`,filename:`File ${i}.pdf`})):[m,other];
 else if(path.includes('/materials/')){if(init?.method==='DELETE')data={success:opts.remove??true};else if(init?.method==='PATCH')data={success:opts.edit??true,status:opts.edit===false?'incomplete':'updated'};else data={...m,can_manage:!opts.readOnly};}
 else if(path.endsWith('/knowledge/answer'))data={answer:'No matching evidence.',grounded:false,sources:[]};
 return new Response(JSON.stringify(data),{status});});return {client:new APIClient(fetcher),fetcher};
}
function mount(element:React.ReactNode,opts:Parameters<typeof fake>[0]={}){const api=fake(opts);const result=render(<AuthProvider api={api.client}>{element}</AuthProvider>);return {...api,...result};}
beforeEach(()=>{nav.params=new URLSearchParams();Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:function(){this.setAttribute('open','');}});Object.defineProperty(HTMLDialogElement.prototype,'close',{configurable:true,value:function(){this.removeAttribute('open');}});});
async function fillUpload(){await screen.findByText('Upload material',{selector:'h1'});await userEvent.upload(screen.getByLabelText('Academic file'),new File(['Synthetic PDF'], 'Synthetic PCA.pdf',{type:'application/pdf'}));for(const [label,value] of [['Course','B.Tech CSE'],['Semester','Semester 7'],['Subject','Machine Learning'],['Unit','Unit 2']])await userEvent.type(screen.getByLabelText(label),value);}
describe('course and hierarchy projections',()=>{
 it('lists only authorized represented courses and real counts',async()=>{mount(<CoursesPage/>);await screen.findByText('B.Tech CSE',{selector:'strong'});expect(screen.getByText(/2 subjects · 2 materials/)).toBeInTheDocument();expect(screen.getByRole('link',{name:'B.Tech CSE'})).toHaveAttribute('href','/courses/B.Tech%20CSE');});
 it('has an actionable course empty state',async()=>{mount(<CoursesPage/>,{empty:true});await screen.findByText('No courses with materials yet');});
 it('renders course detail hierarchy without opaque IDs',async()=>{mount(<CoursesPage course="B.Tech CSE"/>);await screen.findByRole('heading',{name:'Knowledge & materials'});expect(screen.getByText('Unit 2',{selector:'h3'})).toBeInTheDocument();expect(screen.queryByText('synthetic-id')).not.toBeInTheDocument();expect(screen.getByRole('link',{name:'Ask about this course'})).toHaveAttribute('href',scopeURL({course:m.course}));});
 it('does not invent unauthorized course details',async()=>{mount(<CoursesPage course="Unknown"/>);await screen.findByText('Course unavailable');});
 it('normalizes case/whitespace across dependent hierarchy fields',()=>{expect(normalizeHierarchy({course:' b.tech cse ',semester:'semester 7',subject:'machine learning',unit:'unit 2'},[m])).toEqual({course:m.course,semester:m.semester,subject:m.subject,unit:m.unit});});
 it('decodes encoded course names exactly once and handles malformed escapes',()=>{expect(decodeRouteSegment('B.Tech%20CSE')).toBe('B.Tech CSE');expect(decodeRouteSegment('100%25')).toBe('100%');expect(decodeRouteSegment('%broken')).toBe('%broken');});
 it('counts subjects within their semesters deterministically',()=>{expect(projectCourses([other,m])[0].subjects).toBe(2);});
});
describe('material library',()=>{
 it('searches metadata and resets dependent filters',async()=>{mount(<LibraryPage/>);await screen.findByText(m.filename);await userEvent.selectOptions(screen.getByLabelText('Semester'),m.semester);expect(screen.queryByText(other.filename)).not.toBeInTheDocument();await userEvent.selectOptions(screen.getByLabelText('Unit'),m.unit);await userEvent.selectOptions(screen.getByLabelText('Semester'),other.semester);expect(screen.getByLabelText('Unit')).toHaveValue('');expect(screen.getByText(other.filename)).toBeInTheDocument();await userEvent.type(screen.getByRole('searchbox'),'unknown');expect(screen.getByText('No materials match this view')).toBeInTheDocument();});
 it('paginates authorized results without duplicating or hiding the last page',async()=>{mount(<LibraryPage/>,{many:true});await screen.findByText('45 materials · page 1 of 3');expect(screen.getAllByRole('row')).toHaveLength(21);await userEvent.click(screen.getByRole('button',{name:'Next'}));await userEvent.click(screen.getByRole('button',{name:'Next'}));expect(screen.getAllByRole('row')).toHaveLength(6);expect(screen.getByRole('button',{name:'Next'})).toBeDisabled();});
});
describe('protected upload',()=>{
 it('uploads multipart with CSRF and offers scoped knowledge',async()=>{const {fetcher}=mount(<UploadPage/>);await fillUpload();fireEvent.submit(screen.getByLabelText('Academic file').closest('form')!);await screen.findByText(`Material registered: ${m.filename}`);const call=fetcher.mock.calls.find(([,init])=>init?.method==='POST');expect(call?.[1]?.body).toBeInstanceOf(FormData);expect(call?.[1]?.headers).toMatchObject({'X-CSRF-Token':'synthetic-csrf'});expect(call?.[1]?.headers).not.toHaveProperty('Content-Type');expect(screen.getByRole('link',{name:'Ask about this material'})).toHaveAttribute('href','/knowledge?material=synthetic-id');});
 it('reports duplicate without implying successful ingestion',async()=>{mount(<UploadPage/>,{upload:{success:false,duplicate:true,material:null}});await fillUpload();fireEvent.submit(screen.getByLabelText('Academic file').closest('form')!);await screen.findByText(/exact file content is already registered/);expect(screen.queryByText(/Material registered:/)).not.toBeInTheDocument();});
 it('reports ingestion failure without exposing storage internals',async()=>{mount(<UploadPage/>,{upload:{success:false,duplicate:false,material:null}});await fillUpload();fireEvent.submit(screen.getByLabelText('Academic file').closest('form')!);await screen.findByRole('alert');expect(screen.queryByRole('link',{name:'Open material'})).not.toBeInTheDocument();});
 it.each([401,403,413,503])('handles HTTP %s safely',async(status)=>{mount(<UploadPage/>,{failure:status});await fillUpload();fireEvent.submit(screen.getByLabelText('Academic file').closest('form')!);await screen.findByRole('alert');expect(screen.queryByText(/private\/secret/)).not.toBeInTheDocument();});
});
describe('material management',()=>{
 it('shows safe metadata and hides controls for read-only material',async()=>{mount(<MaterialPage identity={m.material_id}/>,{readOnly:true});await screen.findByRole('heading',{name:'Academic placement'});expect(screen.getByText(/Private to its owner/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Delete material'})).not.toBeInTheDocument();});
 it('edits hierarchy only after confirmed backend success',async()=>{const {fetcher}=mount(<MaterialPage identity={m.material_id}/>);await screen.findByRole('button',{name:'Edit academic placement'});await userEvent.click(screen.getByRole('button',{name:'Edit academic placement'}));await userEvent.clear(screen.getByLabelText('Unit'));await userEvent.type(screen.getByLabelText('Unit'),'Unit 3');await userEvent.click(screen.getByRole('button',{name:'Save placement'}));await screen.findByText(/Academic placement updated/);const call=fetcher.mock.calls.find(([,init])=>init?.method==='PATCH');expect(JSON.parse(String(call?.[1]?.body))).toMatchObject({unit:'Unit 3'});});
 it('does not claim success on incomplete hierarchy update',async()=>{mount(<MaterialPage identity={m.material_id}/>,{edit:false});await screen.findByRole('button',{name:'Edit academic placement'});await userEvent.click(screen.getByRole('button',{name:'Edit academic placement'}));await userEvent.click(screen.getByRole('button',{name:'Save placement'}));await screen.findByText(/placement was not updated completely/);});
 it('requires explicit accessible confirmation before deletion',async()=>{const {fetcher}=mount(<MaterialPage identity={m.material_id}/>);await screen.findByRole('button',{name:'Delete material'});await userEvent.click(screen.getByRole('button',{name:'Delete material'}));expect(screen.getByRole('dialog')).toHaveAccessibleName('Delete material?');expect(fetcher.mock.calls.some(([,init])=>init?.method==='DELETE')).toBe(false);await userEvent.click(screen.getByRole('button',{name:'Keep material'}));expect(fetcher.mock.calls.some(([,init])=>init?.method==='DELETE')).toBe(false);await userEvent.click(screen.getByRole('button',{name:'Delete material'}));await userEvent.click(screen.getByRole('button',{name:'Confirm deletion'}));await screen.findByText('Material and its indexed knowledge were removed.');});
 it('surfaces partial deletion without a success claim',async()=>{mount(<MaterialPage identity={m.material_id}/>,{remove:false});await screen.findByRole('button',{name:'Delete material'});await userEvent.click(screen.getByRole('button',{name:'Delete material'}));await userEvent.click(screen.getByRole('button',{name:'Confirm deletion'}));await screen.findByText(/Deletion did not complete/);expect(screen.queryByText('This material is no longer registered')).not.toBeInTheDocument();});
 it('has labelled accessible hierarchy controls',async()=>{const view=mount(<UploadPage/>);await screen.findByLabelText('Course');const result=await axe.run(view.container,{rules:{'color-contrast':{enabled:false},region:{enabled:false}}});expect(result.violations.map(v=>v.id)).toEqual([]);});
});
describe('structured knowledge handoff',()=>{
 it('uses hierarchy URL scope and allows clearing it',async()=>{nav.params=new URLSearchParams({course:m.course,semester:m.semester,subject:m.subject,unit:m.unit});mount(<KnowledgePage/>);await screen.findByRole('option',{name:m.filename});expect(screen.getByLabelText('Unit')).toHaveValue(m.unit);await userEvent.click(screen.getByRole('button',{name:'Clear scope'}));expect(screen.getByLabelText('Course')).toHaveValue('');});
 it('offers upload after no evidence without ungrounded fallback',async()=>{mount(<KnowledgePage/>);await screen.findByRole('option',{name:m.filename});await userEvent.type(screen.getByLabelText('What would you like to understand?'),'Synthetic question');await userEvent.click(screen.getByRole('button',{name:'Ask question'}));await screen.findByRole('link',{name:'Upload relevant material'});expect(screen.queryByRole('heading',{name:'Grounded answer'})).not.toBeInTheDocument();});
});
