import React from 'react';
import {beforeEach,it,expect,vi} from 'vitest';
import {render,screen,waitFor,fireEvent,within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import axe from 'axe-core';
import {APIClient} from '@/lib/api';
import {AuthProvider} from '@/features/auth';
import {ProtectedShell} from '@/components/shell';
import {StudentAnalyticsPage} from '@/features/students';
const nav=vi.hoisted(()=>({params:new URLSearchParams()}));
vi.mock('next/navigation',()=>({useSearchParams:()=>nav.params,usePathname:()=>'/students',useRouter:()=>({replace:vi.fn()})}));
vi.mock('next/link',()=>({default:({href,children,...p}:{href:string}&React.ComponentProps<'a'>)=><a href={href} {...p}>{children}</a>}));
const students=[{analysis_id:'row_0',student_id:'001',student_name:'Synthetic Alpha',latest_marks:80,attendance:90,needs_support:false,incomplete_data:false,reasons:'No concerns',marks_trend:'Not applicable',attendance_trend:'Not applicable'},{analysis_id:'row_1',student_id:'002',student_name:'Synthetic Beta',latest_marks:40,attendance:null,needs_support:true,incomplete_data:true,reasons:'Average marks 40 < threshold 50; Incomplete data: attendance_percent',marks_trend:'Not applicable',attendance_trend:'Not applicable'}];
const summary={mode:'snapshot',total_students:2,class_average_marks:60,average_attendance:90,academic_concerns:1,incomplete_data:1,averages_basis:'Available student averages',marks_available_count:2,attendance_available_count:1};
function api(options:{uploadError?:number;normalizeError?:number;expired?:boolean;trend?:boolean;csrf?:boolean;exportError?:boolean;allInvalid?:boolean}={}){
 let csrf=false;
 const transport=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const path=String(input);const b=init?.body&&!(init.body instanceof FormData)?JSON.parse(String(init.body)):{};let status=200;let data:unknown={};
 if(path.endsWith('/auth/me'))data={professor_id:'synthetic',display_name:'Synthetic Professor',institution_id:'synthetic',department_id:'synthetic'};
 else if(path.endsWith('/auth/csrf'))data={csrf_token:'synthetic-csrf'};
 else if(path.endsWith('/students/upload')){if(options.csrf&&!csrf){csrf=true;return new Response(JSON.stringify({error:{code:'CSRF_REJECTED'}}),{status:403});}status=options.uploadError??200;data={handle:'book',sheets:['CSV','Sheet 2']};}
 else if(path.endsWith('/preview')){status=options.expired?404:200;data={columns:['Roll Number','Name','Attendance','Quiz','Assessment Number'],rows:[{'Roll Number':'001',Name:'Synthetic Alpha',Attendance:'90',Quiz:'80'}],total_rows:30,suggestions:{student_id:{candidates:['Roll Number'],confidence:'High confidence'},student_name:{candidates:['Name'],confidence:'High confidence'},attendance:{candidates:['Attendance'],confidence:'High confidence'},assessments:{candidates:['Quiz'],confidence:'Possible match'}}};}
 else if(path.endsWith('/review'))data={handle:'data',validation:{eligible_rows:2,invalid_rows:1,incomplete_rows:1,excluded_rows:0},issues:[]};
 else if(path.endsWith('/normalize')){status=options.normalizeError??200;data={handle:'data',validation:{eligible_rows:options.allInvalid?0:2,invalid_rows:1,incomplete_rows:1,excluded_rows:0},issues:[{row:4,code:'invalid_mark',severity:'ERROR'}]};}
 else if(path.endsWith('/analyze'))data={students:b.search?students.filter(s=>s.student_name.toLowerCase().includes(b.search.toLowerCase())):b.view==='Incomplete'?[students[1]]:students,summary:{...summary,mode:options.trend?'trend':'snapshot'}};
 else if(path.endsWith('/detail'))data={student:students[b.index],mode:options.trend?'trend':'snapshot',history:[{student_name:students[b.index].student_name,Quiz:students[b.index].latest_marks,attendance_percent:students[b.index].attendance}]};
 else if(path.endsWith('/export')){if(options.exportError)return new Response(JSON.stringify({error:{code:'STORAGE_ERROR',message:'RAW student private'}}),{status:503});return new Response("Synthetic export");}
 else if(init?.method==='DELETE')data={status:'cleared'};
 if(status!==200)data={error:{code:'VALIDATION_ERROR',message:'RAW student private /server/path'}};
 return new Response(JSON.stringify(data),{status});
 });return {client:new APIClient(transport),transport};
}
function mount(options:Parameters<typeof api>[0]={},shell=false){const a=api(options);return {...a,...render(<AuthProvider api={a.client}>{shell?<ProtectedShell><StudentAnalyticsPage/></ProtectedShell>:<StudentAnalyticsPage/>}</AuthProvider>)};}
const file=()=>new File(['synthetic'],'synthetic.csv',{type:'text/csv'});
async function upload(){await screen.findByLabelText(/Student spreadsheet/);fireEvent.change(screen.getByLabelText(/Student spreadsheet/),{target:{files:[file()]}});await screen.findByRole('heading',{name:'Confirm column mapping'});}
async function ready(){await upload();await userEvent.click(screen.getByRole('button',{name:'Validate and analyze'}));await screen.findByRole('heading',{name:'Class Overview'});}
beforeEach(()=>{nav.params=new URLSearchParams();Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:function(){this.setAttribute('open','');}});Object.defineProperty(HTMLDialogElement.prototype,'close',{configurable:true,value:function(){this.removeAttribute('open');}});vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});Object.defineProperty(URL,'createObjectURL',{configurable:true,value:vi.fn(()=>'blob:synthetic')});Object.defineProperty(URL,'revokeObjectURL',{configurable:true,value:vi.fn()});});
it('activates Student Analytics and Smart Assistant navigation',async()=>{mount({},true);await screen.findByRole('link',{name:'Student Analytics'});expect(screen.getByRole('link',{name:'Student Analytics'})).toHaveAttribute('href','/students');expect(screen.getByRole('link',{name:'Smart Assistant'})).toHaveAttribute('href','/assistant');});
it('shows ephemeral empty state and no AI guarantee',async()=>{mount();await screen.findByText(/No dataset loaded/);expect(screen.getByText(/student records are never sent to AI/)).toBeInTheDocument();});
it.each(['csv','xlsx'])('uploads %s through protected multipart boundary',async(ext)=>{const {transport}=mount();await screen.findByLabelText(/Student spreadsheet/);fireEvent.change(screen.getByLabelText(/Student spreadsheet/),{target:{files:[new File(['synthetic'],`synthetic.${ext}`)]}});await screen.findByRole('heading',{name:'Data preview'});const call=transport.mock.calls.find(([p])=>String(p).endsWith('/upload'));expect(call?.[1]?.body).toBeInstanceOf(FormData);expect(call?.[1]?.headers).toMatchObject({'X-CSRF-Token':'synthetic-csrf'});});
it('uses bounded preview and deterministic mapping suggestions',async()=>{mount();await upload();expect(screen.getByText(/First 1 of 30 rows/)).toBeInTheDocument();expect(screen.getByLabelText('Student identifier / roll number')).toHaveValue('Roll Number');expect(screen.getByLabelText('Attendance column')).toHaveValue('Attendance');});
it('permits explicit mapping correction',async()=>{const {transport}=mount();await upload();await userEvent.selectOptions(screen.getByLabelText('Student identifier / roll number'),'');await userEvent.click(screen.getByRole('button',{name:'Validate and analyze'}));await screen.findByRole('heading',{name:'Class Overview'});const call=transport.mock.calls.find(([p])=>String(p).endsWith('/normalize'));expect(JSON.parse(String(call?.[1]?.body)).student_id).toBeNull();});
it('reviews alternate worksheet/header before mapping',async()=>{const {transport}=mount();await upload();await userEvent.selectOptions(screen.getByLabelText('Worksheet'),'Sheet 2');expect(screen.queryByRole('heading',{name:'Confirm column mapping'})).not.toBeInTheDocument();fireEvent.change(screen.getByLabelText('Header row'),{target:{value:'2'}});await userEvent.click(screen.getByRole('button',{name:'Review selected header'}));await screen.findByRole('heading',{name:'Confirm column mapping'});expect(transport.mock.calls.filter(([p])=>String(p).endsWith('/preview')).at(-1)?.[1]?.body).toBe(JSON.stringify({sheet:'Sheet 2',header_row:2}));});
it('supports configured raw marks maximum',async()=>{const {transport}=mount();await upload();await userEvent.selectOptions(screen.getByLabelText('Scale for Quiz'),'raw');fireEvent.change(screen.getByLabelText('Maximum for Quiz'),{target:{value:'50'}});await userEvent.click(screen.getByRole('button',{name:'Validate and analyze'}));await screen.findByRole('heading',{name:'Class Overview'});expect(JSON.parse(String(transport.mock.calls.find(([p])=>String(p).endsWith('/normalize'))?.[1]?.body)).assessments[0]).toMatchObject({scale:'raw',maximum:50});});
it.each([401,403,413,422,503])('handles safe upload HTTP %s',async(uploadError)=>{mount({uploadError});await screen.findByLabelText(/Student spreadsheet/);fireEvent.change(screen.getByLabelText(/Student spreadsheet/),{target:{files:[file()]}});if(uploadError===401)await screen.findByText(/Verifying your professor session/);else await screen.findByRole('alert');expect(screen.queryByText(/RAW student/)).not.toBeInTheDocument();});
it('rejects unsupported files before transport',async()=>{const {transport}=mount();await screen.findByLabelText(/Student spreadsheet/);fireEvent.change(screen.getByLabelText(/Student spreadsheet/),{target:{files:[new File(['x'],'synthetic.xlsm')]}});await screen.findByRole('alert');expect(transport.mock.calls.some(([p])=>String(p).endsWith('/upload'))).toBe(false);});
it('handles expired preview without private details',async()=>{mount({expired:true});await screen.findByLabelText(/Student spreadsheet/);fireEvent.change(screen.getByLabelText(/Student spreadsheet/),{target:{files:[file()]}});await screen.findByText(/temporary dataset has expired/);});
it('displays safe mapping failure',async()=>{mount({normalizeError:422});await upload();await userEvent.click(screen.getByRole('button',{name:'Validate and analyze'}));await screen.findByRole('alert');expect(screen.queryByRole('heading',{name:'Class Overview'})).not.toBeInTheDocument();});
it('shows invalid exclusion counts and incomplete information',async()=>{mount();await ready();expect(screen.getByText(/1 invalid rows excluded/)).toBeInTheDocument();expect(screen.getByText('Row 4: Invalid marks (error)')).toBeInTheDocument();expect(screen.getByText('Missing')).toBeInTheDocument();expect(screen.getByText(/Average marks 40/)).toBeInTheDocument();});
it('shows all-invalid state without reassuring analytics',async()=>{mount({allInvalid:true});await upload();await userEvent.click(screen.getByRole('button',{name:'Validate and analyze'}));await screen.findByText(/No eligible student rows/);expect(screen.queryByRole('heading',{name:'Class Overview'})).not.toBeInTheDocument();});
it('renders authoritative class averages and missing basis',async()=>{mount();await ready();expect(screen.getByText('60')).toBeInTheDocument();expect(screen.getByText(/attendance available for 1 students/)).toBeInTheDocument();});
it('filters by search through backend',async()=>{mount();await ready();await userEvent.type(screen.getByLabelText('Search identifier or name'),'Beta');await userEvent.click(screen.getByRole('button',{name:'Apply filters and thresholds'}));await waitFor(()=>expect(screen.queryByText('Synthetic Alpha')).not.toBeInTheDocument());expect(screen.getByText('Synthetic Beta')).toBeInTheDocument();});
it('uses existing incomplete filter and configurable thresholds',async()=>{const {transport}=mount();await ready();await userEvent.selectOptions(screen.getByLabelText('Student filter'),'Incomplete');fireEvent.change(screen.getByLabelText('Marks attention threshold'),{target:{value:'60'}});await userEvent.click(screen.getByRole('button',{name:'Apply filters and thresholds'}));await waitFor(()=>expect(screen.queryByText('Synthetic Alpha')).not.toBeInTheDocument());expect(JSON.parse(String(transport.mock.calls.filter(([p])=>String(p).endsWith('/analyze')).at(-1)?.[1]?.body))).toMatchObject({view:'Incomplete',marks_threshold:60});});
it('sorts deterministic performance without risk scoring',async()=>{mount();await ready();await userEvent.selectOptions(screen.getByLabelText('Sort displayed students'),'latest_marks');const table=screen.getByRole('table',{name:/Student performance/});expect(within(table).getAllByRole('row')[1]).toHaveTextContent('Synthetic Alpha');});
it('opens individual detail without student identifier in URL',async()=>{const {transport}=mount();await ready();await userEvent.click(screen.getByRole('button',{name:'View student 2'}));await screen.findByRole('region',{name:'Student detail'});const call=transport.mock.calls.find(([p])=>String(p).endsWith('/detail'));expect(call?.[0]).not.toContain('002');expect(JSON.parse(String(call?.[1]?.body)).index).toBe(1);expect(screen.getByRole('table',{name:'Snapshot marks and attendance'})).toBeInTheDocument();});
it.each([false,true])('honestly exposes trend available=%s',async(trend)=>{mount({trend});await ready();expect(screen.getByText(trend?/Trend mode:/ : /Trends are unavailable/)).toBeInTheDocument();});
it('exports applied filters rather than unsaved control edits',async()=>{const {transport}=mount();await ready();await userEvent.type(screen.getByLabelText('Search identifier or name'),'Pending');await userEvent.click(screen.getByRole('button',{name:'Export applied view CSV'}));await screen.findByText(/CSV exported/);expect(JSON.parse(String(transport.mock.calls.find(([p])=>String(p).endsWith('/export'))?.[1]?.body)).search).toBe('');});
it('handles export failure safely',async()=>{mount({exportError:true});await ready();await userEvent.click(screen.getByRole('button',{name:'Export applied view CSV'}));await screen.findByRole('alert');expect(screen.queryByText(/RAW student/)).not.toBeInTheDocument();});
it('requires clear confirmation and removes derived results',async()=>{const {transport}=mount();await ready();await userEvent.click(screen.getByRole('button',{name:'Clear dataset'}));expect(transport.mock.calls.some(([,i])=>i?.method==='DELETE')).toBe(false);await userEvent.click(screen.getByRole('button',{name:'Keep dataset'}));expect(screen.getByRole('heading',{name:'Class Overview'})).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Clear dataset'}));await userEvent.click(screen.getByRole('button',{name:'Confirm clear'}));await screen.findByText(/Temporary dataset cleared/);expect(screen.queryByText('Synthetic Alpha')).not.toBeInTheDocument();});
it('requires replacement confirmation',async()=>{mount();await ready();await userEvent.click(screen.getByRole('button',{name:'Replace dataset'}));expect(screen.getByRole('dialog')).toHaveTextContent('Replace this dataset?');await userEvent.click(screen.getByRole('button',{name:'Confirm replacement'}));await screen.findByText(/No dataset loaded/);});
it('retries only CSRF rejection before upload',async()=>{const {transport}=mount({csrf:true});await upload();expect(transport.mock.calls.filter(([p])=>String(p).endsWith('/upload'))).toHaveLength(2);});
it('has accessible mapping controls and tabular alternatives',async()=>{const {container}=mount();await upload();const result=await axe.run(container,{rules:{'color-contrast':{enabled:false},region:{enabled:false}}});expect(result.violations).toEqual([]);});
it('does not persist student data in browser storage',async()=>{const local=vi.spyOn(Storage.prototype,'setItem');mount();await ready();expect(local).not.toHaveBeenCalled();local.mockRestore();});

it('logout hides private records and returns to session boundary',async()=>{mount({},true);await ready();await userEvent.click(screen.getByRole('button',{name:'Sign out'}));await screen.findByText(/Sign in to access/);expect(screen.queryByText('Synthetic Alpha')).not.toBeInTheDocument();});
it('clear releases an expired preview locally',async()=>{mount({expired:true});await screen.findByLabelText(/Student spreadsheet/);fireEvent.change(screen.getByLabelText(/Student spreadsheet/),{target:{files:[file()]}});await screen.findByRole('alert');await userEvent.click(screen.getByRole('button',{name:'Clear dataset'}));await userEvent.click(screen.getByRole('button',{name:'Confirm clear'}));await screen.findByText(/No dataset loaded/);});

it('opens the server-owned student dataset handed off by Assistant',async()=>{nav.params=new URLSearchParams({workspace:'data',view:'Incomplete'});mount();await screen.findByRole('heading',{name:'Class Overview'});expect(screen.getByText('Synthetic Beta')).toBeInTheDocument();expect(screen.queryByText('Synthetic Alpha')).not.toBeInTheDocument();});
