import React from "react";
import { beforeEach,describe,it,expect,vi } from "vitest";
import { render,screen,waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import axe from "axe-core";
import { APIClient } from "@/lib/api";
import { AuthProvider,useAuth } from "@/features/auth";
import { DashboardPage } from "@/features/dashboard";
import { KnowledgePage } from "@/features/knowledge";
import { LibraryPage } from "@/features/library";
import { LoginPage } from "@/features/login";
import { ProtectedShell } from "@/components/shell";
const nav=vi.hoisted(()=>({pathname:"/home",replace:vi.fn(),params:new URLSearchParams()}));
vi.mock("next/navigation",()=>({usePathname:()=>nav.pathname,useRouter:()=>({replace:nav.replace}),useSearchParams:()=>nav.params}));
vi.mock("next/link",()=>({default:({href,children,...props}:{href:string}&React.ComponentProps<"a">)=><a href={href} {...props}>{children}</a>}));
const professor={professor_id:"opaque-professor",display_name:"Professor Synthetic",institution_id:"opaque-institute",department_id:"opaque-department"};
const material={material_id:"opaque-material",filename:"PCA.pdf",course:"B.Tech CSE",semester:"Semester 7",subject:"Machine Learning",unit:"Unit 2",created_at:"2026-10-05T10:00:00Z"};
const status={provider:"ollama",preferred_model:"qwen2.5:3b",effective_model:null,fallback_active:null,embedding:"all-MiniLM-L6-v2",candidate_k:15,final_k:5,threshold:.5,reranker:false,router:false};
const dashboard={material_count:1,courses:["B.Tech CSE"],materials:[material],saved_drafts:[],activity:[]};
function response(value:unknown,status=200){return new Response(JSON.stringify(value),{status});}
function api(options:{unauth?:boolean;empty?:boolean;answer?:unknown;answerStatus?:number;meFailure?:number}={}){
 const transport=vi.fn(async(input:RequestInfo|URL,requestOptions?:RequestInit)=>{void requestOptions;const path=String(input);if(path.endsWith("/auth/me"))return response(options.unauth?{error:{code:"UNAUTHENTICATED"}}:professor,options.unauth?401:options.meFailure??200);if(path.endsWith("/auth/csrf"))return response({csrf_token:"synthetic-csrf"});if(path.endsWith("/auth/dev-login"))return response({csrf_token:"login-csrf"});if(path.endsWith("/auth/logout"))return response({status:"signed_out"});if(path.endsWith("/dashboard"))return response(options.empty?{...dashboard,material_count:0,courses:[],materials:[]}:dashboard);if(path.endsWith("/materials"))return response(options.empty?[]:[material]);if(path.endsWith("/system/ai"))return response(status);if(path.endsWith("/knowledge/answer"))return response(options.answer??{answer:"PCA finds useful directions in the data.",grounded:true,sources:[{source:"PCA.pdf",material_id:material.material_id}]},options.answerStatus??200);return response({error:{code:"NOT_FOUND"}},404);});return {client:new APIClient(transport),transport};
}
function SessionProbe(){const auth=useAuth();return <><p>{auth.session.status}</p><button onClick={()=>{void auth.logout();}}>Log out</button></>;}
beforeEach(()=>{nav.pathname="/home";nav.params=new URLSearchParams();nav.replace.mockReset();});
describe("backend-authoritative sessions",()=>{
 it("starts loading and resolves /me",async()=>{const {client,transport}=api();render(<AuthProvider api={client}><SessionProbe/></AuthProvider>);expect(screen.getByText("loading")).toBeInTheDocument();await screen.findByText("authenticated");expect(transport.mock.calls[0][0]).toBe("/api/v1/auth/me");});
 it("redirects unauthenticated users without private content",async()=>{render(<AuthProvider api={api({unauth:true}).client}><ProtectedShell><p>Private course content</p></ProtectedShell></AuthProvider>);await waitFor(()=>expect(nav.replace).toHaveBeenCalledWith("/login"));expect(screen.queryByText("Private course content")).not.toBeInTheDocument();});
 it("hides private workspace when identity cannot be verified",async()=>{render(<AuthProvider api={api({meFailure:503}).client}><ProtectedShell><p>Private course content</p></ProtectedShell></AuthProvider>);await screen.findByRole("alert");expect(screen.queryByText("Private course content")).not.toBeInTheDocument();});
 it("logout calls backend and clears professor state",async()=>{const {client,transport}=api();render(<AuthProvider api={client}><SessionProbe/></AuthProvider>);await screen.findByText("authenticated");await userEvent.click(screen.getByRole("button",{name:"Log out"}));await screen.findByText("unauthenticated");expect(nav.replace).toHaveBeenCalledWith("/login");expect(transport.mock.calls.map(([p])=>p)).toContain("/api/v1/auth/logout");});
 it("rechecks identity on navigation before exposing children",async()=>{const {client,transport}=api();const view=render(<AuthProvider api={client}><ProtectedShell><p>Private course content</p></ProtectedShell></AuthProvider>);await screen.findByText("Private course content");nav.pathname="/knowledge";view.rerender(<AuthProvider api={client}><ProtectedShell><p>Other private page</p></ProtectedShell></AuthProvider>);expect(screen.queryByText("Other private page")).not.toBeInTheDocument();await screen.findByText("Other private page");expect(transport.mock.calls.filter(([p])=>String(p).endsWith("/auth/me"))).toHaveLength(2);});
 it("never persists session or professor state in browser storage",async()=>{const write=vi.spyOn(Storage.prototype,"setItem");render(<AuthProvider api={api().client}><SessionProbe/></AuthProvider>);await screen.findByText("authenticated");await userEvent.click(screen.getByRole("button",{name:"Log out"}));await screen.findByText("unauthenticated");expect(write).not.toHaveBeenCalled();});
});
describe("real dashboard/library surfaces",()=>{
 it("renders backend materials without fabricated meetings",async()=>{render(<AuthProvider api={api().client}><ProtectedShell><DashboardPage/></ProtectedShell></AuthProvider>);await screen.findByText("PCA.pdf");expect(screen.getByText("Registered materials")).toBeInTheDocument();expect(screen.queryByText(/meeting at|deadline|student alert/i)).not.toBeInTheDocument();expect(screen.getByText(/Preferred model: qwen2.5:3b/)).toBeInTheDocument();expect(screen.queryByText("opaque-professor")).not.toBeInTheDocument();});
 it("shows honest empty states",async()=>{render(<AuthProvider api={api({empty:true}).client}><ProtectedShell><DashboardPage/></ProtectedShell></AuthProvider>);await screen.findByText("No materials uploaded yet");expect(screen.getByText("No saved documents yet")).toBeInTheDocument();expect(screen.getByText("No recent activity")).toBeInTheDocument();});
 it("browses hierarchy metadata and filters materials",async()=>{render(<AuthProvider api={api().client}><ProtectedShell><LibraryPage/></ProtectedShell></AuthProvider>);await screen.findByText("PCA.pdf");expect(screen.getByText("Semester 7",{selector:"small"})).toBeInTheDocument();expect(screen.getByText("Unit 2",{selector:"small"})).toBeInTheDocument();await userEvent.type(screen.getByRole("searchbox"),"unknown");expect(screen.getByText("No materials match this view")).toBeInTheDocument();});
 it("has semantic landmarks, labels and accessible names",async()=>{const view=render(<AuthProvider api={api().client}><ProtectedShell><DashboardPage/></ProtectedShell></AuthProvider>);await screen.findByText("PCA.pdf");const result=await axe.run(view.container,{rules:{"color-contrast":{enabled:false}}});expect(result.violations.map((v)=>v.id)).toEqual([]);expect(screen.getByRole("main")).toBeInTheDocument();expect(screen.getByRole("button",{name:"Open navigation"})).toBeInTheDocument();});
});
describe("knowledge workflow",()=>{
 async function ask(){await screen.findByRole("option",{name:"PCA.pdf"});await userEvent.type(screen.getByLabelText("What would you like to understand?"),"Explain PCA");await userEvent.click(screen.getByRole("button",{name:"Ask question"}));}
 it("submits real API shape and renders grounded answer with sources",async()=>{const {client,transport}=api();render(<AuthProvider api={client}><KnowledgePage/></AuthProvider>);await ask();await screen.findByText("PCA finds useful directions in the data.");expect(screen.getByRole("heading",{name:"Source references"})).toBeInTheDocument();const call=transport.mock.calls.find(([p])=>String(p).endsWith("/knowledge/answer"));expect(call).toBeTruthy();});
 it("renders no-evidence state honestly",async()=>{render(<AuthProvider api={api({answer:{answer:"No sufficiently relevant information was found.",grounded:false,sources:[]}}).client}><KnowledgePage/></AuthProvider>);await ask();await screen.findByRole("heading",{name:"Insufficient matching material"});expect(screen.queryByRole("heading",{name:"Source references"})).not.toBeInTheDocument();});
 it("handles provider failure with a safe retry",async()=>{render(<AuthProvider api={api({answer:{error:{code:"PROVIDER_UNAVAILABLE",message:"SQL private secret"}},answerStatus:503}).client}><KnowledgePage/></AuthProvider>);await ask();await screen.findByRole("alert");expect(screen.queryByText(/SQL private/)).not.toBeInTheDocument();expect(screen.getByRole("button",{name:"Try again"})).toBeInTheDocument();});
 it("passes only supported hierarchy filters",async()=>{const {client,transport}=api();render(<AuthProvider api={client}><KnowledgePage/></AuthProvider>);await screen.findByRole("option",{name:"PCA.pdf"});await userEvent.selectOptions(screen.getByLabelText("Course"),"B.Tech CSE");await userEvent.type(screen.getByLabelText("What would you like to understand?"),"PCA");await userEvent.click(screen.getByRole("button",{name:"Ask question"}));await screen.findByText("PCA finds useful directions in the data.");const call=transport.mock.calls.find(([p])=>String(p).endsWith("/knowledge/answer"));expect(JSON.parse(String(call?.[1]?.body))).toMatchObject({filters:{course:"B.Tech CSE"}});});
 it("escapes model-generated markup",async()=>{render(<AuthProvider api={api({answer:{answer:'<script>alert("private")</script>',grounded:true,sources:[]}}).client}><KnowledgePage/></AuthProvider>);await ask();await screen.findByText('<script>alert("private")</script>');expect(document.querySelector("script")).toBeNull();});
 it("has accessible question form labels",async()=>{const view=render(<AuthProvider api={api().client}><KnowledgePage/></AuthProvider>);await screen.findByRole("option",{name:"PCA.pdf"});const result=await axe.run(view.container,{rules:{"color-contrast":{enabled:false},region:{enabled:false}}});expect(result.violations.map((v)=>v.id)).toEqual([]);});
});
describe("development login",()=>{
 it("marks development auth explicitly and never has password input",()=>{render(<AuthProvider api={api({unauth:true}).client}><LoginPage enabled aliases={["professor-a"]}/></AuthProvider>);expect(screen.getByText("Development authentication only")).toBeInTheDocument();expect(screen.getByLabelText("Development professor")).toBeInTheDocument();expect(document.querySelector('input[type="password"]')).toBeNull();});
 it("does not show a development selector when disabled",()=>{render(<AuthProvider api={api({unauth:true}).client}><LoginPage enabled={false} aliases={[]}/></AuthProvider>);expect(screen.queryByLabelText("Development professor")).not.toBeInTheDocument();expect(screen.getByText("Sign-in is not configured")).toBeInTheDocument();});
});
