"use client";
import {useCallback,useState} from "react";
import {useAuth} from "@/features/auth";
import {useResource} from "@/features/use-resource";
import {PageHeading,Loading,ErrorNotice,Empty} from "@/components/states";
export function ActivityPage(){const {client}=useAuth();const [category,setCategory]=useState('All');const [cursors,setCursors]=useState<(number|null)[]>([null]);const before=cursors[cursors.length-1];const load=useCallback((signal:AbortSignal)=>client.activityPage(category,before,signal),[client,category,before]);const resource=useResource(load);
 return <><PageHeading eyebrow="Your workspace history" title="Activity Center" description="Recent actor-scoped workspace actions. This view contains safe action labels and timestamps, never prompts, student records or generated content."/><section className="panel"><div className="field"><label htmlFor="activity-category">Activity category</label><select id="activity-category" value={category} onChange={e=>{setCategory(e.target.value);setCursors([null]);}}>{['All','Materials','Assessments','Documents','Student Analytics','Workspace'].map(c=><option key={c}>{c}</option>)}</select></div>
 {resource.loading?<Loading label="Loading your activity…"/>:resource.error?<ErrorNotice message={resource.error} retry={resource.retry}/>:!resource.data?.items.length?<Empty title="No recent activity yet" detail="No recorded actions match this view. Events are shown only when actually recorded."/>:<ol className="activity-center" aria-label="Recent workspace actions">{resource.data.items.map((item,i)=><li key={`${item.timestamp}-${i}`}><div><strong>{item.action}</strong><span className="badge">{item.category}</span></div>{item.timestamp==='Time unavailable'?<span>Time unavailable</span>:<time dateTime={item.timestamp}>{new Date(item.timestamp).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})}</time>}</li>)}</ol>}
 <div className="student-actions"><button className="button secondary" disabled={resource.loading||cursors.length===1} onClick={()=>setCursors(cursors.slice(0,-1))}>Newer activity</button><span>Page {cursors.length} · newest first</span><button className="button secondary" disabled={resource.loading||!resource.data?.next_cursor} onClick={()=>setCursors([...cursors,resource.data!.next_cursor])}>Older activity</button></div><p className="footnote">Up to 20 events per page. Categories reflect existing event codes; not every interaction creates an event.</p></section></>;
}
