'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {useAuth} from '@/features/auth';
import {useResource} from '@/features/use-resource';
import {PageHeading,Loading,Empty,ErrorNotice} from '@/components/states';
import {APIError} from '@/lib/api';
import {options} from '@/lib/academic';
import type {Assessment,AssessmentRequest,Material,QuestionEdit} from '@/types/api';
const types=['MCQ','Descriptive'];const difficulties=['Easy','Medium','Hard'];const blooms=['Remember','Understand','Apply','Analyze','Evaluate','Create'];
const counts=(keys:string[],first:number)=>Object.fromEntries(keys.map((k,i)=>[k,i===0?first:0]));
function diagnostic(error:unknown){if(!(error instanceof APIError))return 'The assessment request could not complete. Review the request and try again.';const messages:Record<string,string>={INVALID_JSON:'EduAgent could not produce a usable structured response. Nothing invalid was saved.',SCHEMA_INVALID:'The generated response did not match the required format. Nothing invalid was saved.',PRODUCT_VALIDATION_FAILED:'Assessment requirements were not satisfied. Correct your request or edits and try again.',INSUFFICIENT_EVIDENCE:'Not enough matching evidence was found for every selected Unit/material. Broaden scope, adjust the topic or upload matching material.',PROVIDER_ERROR:'The local AI service could not complete the request. Check its availability.',TIMEOUT:'The local AI service took too long to respond. Try a smaller request or try later.'};return messages[error.category??'']??messages[error.code]??error.message;}
const edits=(a:Assessment):QuestionEdit[]=>a.questions.map(q=>({question_text:q.question_text,marks:q.marks,options:{...q.options},correct_answer:q.correct_answer,model_answer:q.model_answer}));
export function AssessmentPage(){const params=useSearchParams();const {client}=useAuth();const load=useCallback((signal:AbortSignal)=>client.materials(signal),[client]);const library=useResource(load);return <><PageHeading eyebrow="Professor authoring" title="Assessment Studio" description="Configure a grounded quiz or question paper, validate it, review questions and export the professor-approved result."/>{library.loading?<Loading label="Loading authorized academic scope…"/>:library.error?<ErrorNotice message={library.error} retry={library.retry}/>:!library.data?.length?<Empty title="Academic material is required" detail="Upload authorized teaching material before generating a grounded assessment." href="/library/upload" action="Upload material"/>:<AssessmentWorkspace key={params.toString()} materials={library.data}/>}</>;}
function AssessmentWorkspace({materials}:{materials:Material[]}){
 const {client}=useAuth();const params=useSearchParams();const selected=materials.find(m=>m.material_id===params.get('material'));const first=selected??materials.find(m=>m.course===params.get('course'))??materials[0];
 const [scope,setScope]=useState(()=>({course:params.get('course')??first.course,semester:params.get('semester')??first.semester,subject:params.get('subject')??first.subject}));const [units,setUnits]=useState<string[]>([params.get('unit')??first.unit]);const [ids,setIds]=useState<string[]>(params.get('material')?[params.get('material')!]:[]);
 const [mode,setMode]=useState<'Quiz'|'Question Paper'>('Quiz');const [title,setTitle]=useState('Academic Assessment');const [institution,setInstitution]=useState('');const [topic,setTopic]=useState('Key concepts and applications');const [instructions,setInstructions]=useState('Answer all questions.');const [target,setTarget]=useState(2);const [questionTypes,setTypes]=useState(counts(types,2));const [difficulty,setDifficulty]=useState(counts(difficulties,2));const [bloom,setBloom]=useState(counts(blooms,2));const [pyq,setPYQ]=useState<File|null>(null);const pyqInput=useRef<HTMLInputElement>(null);
 const [result,setResult]=useState<Assessment|null>(null);const [draft,setDraft]=useState<QuestionEdit[]>([]);const [answerKey,setAnswerKey]=useState(false);const [pending,setPending]=useState(false);const [saving,setSaving]=useState(false);const [exporting,setExporting]=useState(false);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);const controller=useRef<AbortController|null>(null);const review=useRef<HTMLElement>(null);const discard=useRef<HTMLDialogElement>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 const total=Object.values(questionTypes).reduce((a,b)=>a+b,0);const eligible=materials.filter(m=>m.course===scope.course&&m.semester===scope.semester&&m.subject===scope.subject);const availableUnits=[...new Set(eligible.map(m=>m.unit))].sort();const available=eligible.filter(m=>units.includes(m.unit));const dirty=!!result&&JSON.stringify(draft)!==JSON.stringify(edits(result));const editTotal=draft.reduce((a,q)=>a+q.marks,0);
 const validCounts=total>0&&total<=100&&target>=total&&target<=10000&&Object.values(difficulty).reduce((a,b)=>a+b,0)===total&&Object.values(bloom).reduce((a,b)=>a+b,0)===total;
 const validScope=units.length>0&&units.every(u=>availableUnits.includes(u))&&ids.every(id=>available.some(m=>m.material_id===id));const locked=pending||!!result;
 const changeScope=(key:'course'|'semester'|'subject',value:string)=>{const next={...scope,[key]:value};if(key==='course'){next.semester='';next.subject='';}if(key==='semester')next.subject='';setScope(next);setUnits([]);setIds([]);};
 const group=(label:string,keys:string[],values:Record<string,number>,update:(v:Record<string,number>)=>void)=><fieldset className="count-controls" disabled={locked}><legend>{label}</legend>{keys.map(k=><div className="field" key={k}><label htmlFor={`${label}-${k}`}>{k} count</label><input id={`${label}-${k}`} type="number" min={0} max={100} step={1} value={values[k]} onChange={e=>update({...values,[k]:Number(e.target.value)})}/></div>)}</fieldset>;
 async function generate(){if(pending||!validCounts||!validScope||result)return;controller.current?.abort();const abort=new AbortController();controller.current=abort;setPending(true);setError(null);setNotice(null);
 try{let pyqHandle:string|null=null;if(pyq){if(!['pdf','png','jpg','jpeg'].includes(pyq.name.split('.').at(-1)?.toLowerCase()??'')||pyq.size>10*1024*1024||!pyq.size){setError('Use a non-empty PDF, PNG, JPG or JPEG PYQ within 10 MiB.');return;}const guidance=await client.uploadPYQ(pyq);if(abort.signal.aborted)return;pyqHandle=guidance.handle;}
 const body:AssessmentRequest={assessment_type:mode,...scope,units,material_ids:ids,question_types:questionTypes,difficulties:difficulty,blooms:bloom,total_questions:total,total_marks:target,title,institution,instructions,topic,pyq_handle:pyqHandle};const a=await client.generateAssessment(body,abort.signal);if(!abort.signal.aborted){setResult(a);setDraft(edits(a));requestAnimationFrame(()=>review.current?.focus());}}
 catch(e){if(!abort.signal.aborted)setError(diagnostic(e));}finally{if(!abort.signal.aborted)setPending(false);}}
 const stop=()=>{controller.current?.abort();setPending(false);setNotice('Stopped waiting. Server inference may still finish; no backend cancellation was sent. Any unreachable result expires with the session.');};
 async function save(){if(!result||saving)return;setSaving(true);setError(null);setNotice(null);try{const updated=await client.editAssessment(result.handle,result.revision,draft);setResult(updated);setDraft(edits(updated));setNotice('Professor edits validated. Review academic accuracy and evidence support before use.');}catch(e){setError(diagnostic(e));}finally{setSaving(false);}}
 async function download(format:'pdf'|'docx'){if(!result||dirty||saving||exporting)return;setExporting(true);setError(null);try{const blob=await client.exportAssessment(result.handle,format,answerKey);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${result.title.replace(/[^\p{L}\p{N} _-]/gu,'').trim().slice(0,80)||'Academic Assessment'}${answerKey?' - Answer Key':''}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(diagnostic(e));}finally{setExporting(false);}}
 async function reset(){if(!result||saving||exporting)return;setSaving(true);setError(null);try{await client.discardAssessment(result.handle);setResult(null);setDraft([]);setAnswerKey(false);setNotice(null);discard.current?.close();}catch(e){setError(diagnostic(e));}finally{setSaving(false);}}
 const update=(i:number,values:Partial<QuestionEdit>)=>setDraft(current=>current.map((q,index)=>index===i?{...q,...values}:q));
 return <><p className="footnote">Session workspace: generated assessments and unsaved edits can disappear on navigation, logout, expiry or server restart. The professor remains the final authority.</p>{error&&<ErrorNotice message={error}/>} {notice&&<p role="status" className="notice">{notice}</p>}
 <section className="panel"><h2>Configure assessment</h2><form onSubmit={e=>{e.preventDefault();void generate();}}><fieldset className="scope-controls" disabled={locked}><legend>Teaching evidence</legend>{(['course','semester','subject'] as const).map(k=><div className="field" key={k}><label htmlFor={`assessment-${k}`}>{k.charAt(0).toUpperCase()+k.slice(1)}</label><select id={`assessment-${k}`} required value={scope[k]} onChange={e=>changeScope(k,e.target.value)}><option value="">Select {k}</option>{options(materials,scope,k).map(v=><option key={v}>{v}</option>)}</select></div>)}</fieldset><p className="field-hint">Choose one semester and subject, then one or more units. A course handoff does not generate across every subject automatically.</p>
 <fieldset className="check-controls" disabled={locked}><legend>Units</legend>{availableUnits.map(u=><label key={u}><input type="checkbox" checked={units.includes(u)} onChange={e=>{setUnits(e.target.checked?[...units,u]:units.filter(v=>v!==u));setIds([]);}}/>{u}</label>)}</fieldset><fieldset className="check-controls" disabled={locked}><legend>Specific materials (optional)</legend>{available.map(m=><label key={m.material_id}><input type="checkbox" checked={ids.includes(m.material_id)} onChange={e=>setIds(e.target.checked?[...ids,m.material_id]:ids.filter(id=>id!==m.material_id))}/>{m.filename}</label>)}</fieldset>{!validScope&&<p role="status" className="notice">Choose available academic scope. An unavailable URL material is not substituted silently.</p>}
 <fieldset className="check-controls" disabled={locked}><legend>Assessment mode</legend>{(['Quiz','Question Paper'] as const).map(v=><label key={v}><input type="radio" name="assessment-mode" checked={mode===v} onChange={()=>setMode(v)}/>{v}</label>)}</fieldset><fieldset className="scope-controls" disabled={locked}><legend>Paper details</legend><div className="field"><label htmlFor="assessment-title">Title</label><input id="assessment-title" required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></div><div className="field"><label htmlFor="assessment-institution">Institution (optional)</label><input id="assessment-institution" maxLength={200} value={institution} onChange={e=>setInstitution(e.target.value)}/></div><div className="field"><label htmlFor="assessment-topic">Focus / topic</label><input id="assessment-topic" required maxLength={200} value={topic} onChange={e=>setTopic(e.target.value)}/></div><div className="field"><label htmlFor="assessment-target">Target total marks</label><input id="assessment-target" type="number" min={1} max={10000} step={1} value={target} onChange={e=>setTarget(Number(e.target.value))}/></div><div className="field material-scope"><label htmlFor="assessment-instructions">Student instructions</label><textarea id="assessment-instructions" required maxLength={1000} value={instructions} onChange={e=>setInstructions(e.target.value)}/></div></fieldset>
 {group('Question types',types,questionTypes,setTypes)}{group('Intended difficulty',difficulties,difficulty,setDifficulty)}{group('Bloom distribution',blooms,bloom,setBloom)}<p className="notice">Questions: {total} · Target marks: {target}. {validCounts?`Initial deterministic allocation: ${Math.floor(target/total)} marks each, with ${target%total} leading questions receiving one additional mark.`:'Question, difficulty and Bloom counts must agree; target marks must allow at least one mark per question.'}</p>
 <div className="field"><label htmlFor="assessment-pyq">Optional PYQ style guidance</label><input ref={pyqInput} id="assessment-pyq" disabled={locked} type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={e=>setPYQ(e.target.files?.[0]??null)}/>{pyq&&<button className="text-button" type="button" disabled={locked} onClick={()=>{setPYQ(null);if(pyqInput.current)pyqInput.current.value="";}}>Remove PYQ guidance</button>}<p className="field-hint">PYQ is temporary style/pattern guidance, not teaching evidence. Local extraction only; it is never registered in the material library.</p></div><button className="button primary" disabled={locked||!validScope||!validCounts} type="submit">{pending?'Generating and validating assessment…':'Generate assessment'}</button>{pending&&<><p role="status">Generating and validating assessment… No intermediate progress phases are exposed.</p><button className="text-button" type="button" onClick={stop}>Stop waiting</button></>}</form></section>
 {result&&<section className="panel assessment-review" ref={review} tabIndex={-1} aria-labelledby="assessment-review-title"><div className="section-heading"><h2 id="assessment-review-title">Review: {result.title}</h2><span className={`badge ${dirty?"warning":"success"}`}>{dirty?'Unvalidated local edits':'Validated structure'}</span></div><p>{result.questions.length} questions · Current marks: {editTotal} · Target marks: {result.total_marks}</p><p className="footnote">{dirty?'Revalidate before export. The previous validated server version is retained.':result.professor_edited?'Professor edits validated; evidence references retained. Review academic support.':'Marks and requested distributions verified; answer key and evidence references validated.'} Always review factual accuracy before use.</p>{editTotal!==result.total_marks&&<p role="alert" className="notice">Current marks do not match the configured target.</p>}
 <div className="quick-actions" role="group" aria-label="Review display"><button className="button" aria-pressed={!answerKey} onClick={()=>setAnswerKey(false)}>Question Paper view</button><button className="button" aria-pressed={answerKey} onClick={()=>setAnswerKey(true)}>Answer Key / Review</button></div>
 {result.questions.map((question,i)=>{const q=draft[i];return <article className="question-editor" key={question.question_number}><h3>Question {question.question_number} · {question.question_type}</h3><p className="field-hint">Intended {question.difficulty} · {question.bloom_level}</p><div className="field"><label htmlFor={`q-${i}-text`}>Question {i+1} text</label><textarea id={`q-${i}-text`} maxLength={6000} value={q.question_text} disabled={saving||exporting} onChange={e=>update(i,{question_text:e.target.value})}/></div><div className="field"><label htmlFor={`q-${i}-marks`}>Question {i+1} marks</label><input id={`q-${i}-marks`} type="number" min={1} max={10000} step={1} value={q.marks} disabled={saving||exporting} onChange={e=>update(i,{marks:Number(e.target.value)})}/></div>{question.question_type==='MCQ'&&<fieldset className="count-controls" disabled={saving||exporting}><legend>Question {i+1} options</legend>{['A','B','C','D'].map(letter=><div className="field" key={letter}><label htmlFor={`q-${i}-${letter}`}>Question {i+1} option {letter}</label><input id={`q-${i}-${letter}`} maxLength={2000} value={q.options[letter]??''} onChange={e=>update(i,{options:{...q.options,[letter]:e.target.value}})}/></div>)}</fieldset>}{answerKey&&<div className="answer-key-editor">{question.question_type==='MCQ'&&<div className="field"><label htmlFor={`q-${i}-correct`}>Question {i+1} correct answer</label><select id={`q-${i}-correct`} value={q.correct_answer} disabled={saving||exporting} onChange={e=>update(i,{correct_answer:e.target.value})}>{['A','B','C','D'].map(letter=><option key={letter}>{letter}</option>)}</select></div>}<div className="field"><label htmlFor={`q-${i}-answer`}>Question {i+1} reference answer</label><textarea id={`q-${i}-answer`} maxLength={6000} disabled={saving||exporting} value={q.model_answer} onChange={e=>update(i,{model_answer:e.target.value})}/></div></div>}</article>;})}
 <div className="quick-actions"><button className="button primary" disabled={!dirty||saving} onClick={()=>{void save();}}>{saving?'Validating edits…':'Validate professor edits'}</button><button className="button" disabled={dirty||saving||exporting} onClick={()=>{void download('pdf');}}>Export PDF</button><button className="button" disabled={dirty||saving||exporting} onClick={()=>{void download('docx');}}>Export DOCX</button><button className="button" disabled={saving||exporting} onClick={()=>{if(dirty)discard.current?.showModal();else void reset();}}>New assessment</button></div><p className="footnote">Export uses the displayed Question Paper or Answer Key view. Exports come from the validated server workspace. Save downloaded files before leaving.</p></section>}
 <dialog ref={discard} className="confirmation-dialog" aria-labelledby="discard-assessment-title"><h2 id="discard-assessment-title">Discard your assessment edits?</h2><p>Your local edits and current session assessment will be discarded.</p><button className="button" autoFocus onClick={()=>discard.current?.close()}>Keep editing</button><button className="button danger" disabled={saving||exporting} onClick={()=>{void reset();}}>Discard and start new</button></dialog><p className="footnote">Question removal, single-question AI replacement and manual additions are deferred to preserve fixed distributions and explicit provenance.</p><Link href="/library/upload">Upload additional teaching material</Link></>;
}
