"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {useAuth} from "@/features/auth";
import {useResource} from "@/features/use-resource";
import {PageHeading,Loading,ErrorNotice} from "@/components/states";
import {APIError} from "@/lib/api";
import type {ActionType,Preview,Execution} from "@/types/assistant";
const labels:Record<ActionType,string>={ASK_KNOWLEDGE:"Ask course material",CREATE_ASSESSMENT:"Create assessment",CREATE_DOCUMENT:"Draft document",ANALYZE_STUDENTS:"Review student analytics locally",NAVIGATE:"Open workspace"};
const destinations=new Set(['/home','/library/upload','/knowledge','/assessment','/documents','/students','/activity']);
const fields:Record<string,string>={question:'Academic question',document_type:'Document type',description:'Document purpose',assessment_type:'Assessment type','scope.course':'Course','scope.semester':'Semester','scope.subject':'Subject','scope.units':'Units',question_types:'Question types and counts',difficulties:'Difficulty distribution',blooms:'Bloom distribution',total_questions:'Question count',total_marks:'Total marks',loaded_student_dataset:'A temporary dataset from Student Analytics',view:'Student view',page:'Workspace destination'};
function safe(error:unknown){if(!(error instanceof APIError))return 'The assistant could not complete this operation. Review the request and try again.';const messages:Record<string,string>={INVALID_JSON:'EduAgent could not produce a usable plan. Nothing was executed.',SCHEMA_INVALID:'The proposed plan did not match the supported format. Nothing was executed.',PRODUCT_VALIDATION_FAILED:'The proposed plan did not satisfy the supported requirements. Review your request.',UNSUPPORTED_OPERATION:'This request is not supported. Use an available workspace; external, destructive and personalized student AI actions are unavailable.',PROVIDER_ERROR:'The local AI service is unavailable. Nothing was executed.',TIMEOUT:'The local AI service took too long to respond. Nothing was executed.',INSUFFICIENT_EVIDENCE:'Not enough matching academic material was found. Adjust the academic scope.'};return messages[error.category??'']??messages[error.code]??error.message;}
function scope(parameters:Record<string,unknown>){const p=parameters.scope&&typeof parameters.scope==='object'?parameters.scope as Record<string,unknown>:parameters.filters&&typeof parameters.filters==='object'?parameters.filters as Record<string,unknown>:parameters;return ['course','semester','subject','unit','units','document_type','view','page'].flatMap(k=>typeof p[k]==='string'?[String(p[k])]:Array.isArray(p[k])&&p[k].every(v=>typeof v==='string')?[p[k].join(', ')]:[]).join(' → ');}
export function AssistantPage(){
 const {client}=useAuth();const router=useRouter();const load=useCallback((signal:AbortSignal)=>client.studentWorkspaces(signal),[client]);const datasets=useResource(load);
 const [request,setRequest]=useState('');const [student,setStudent]=useState('');const [plannedStudent,setPlannedStudent]=useState('');const [signature,setSignature]=useState('');const [plan,setPlan]=useState<Preview|null>(null);const [report,setReport]=useState<Execution|null>(null);const [approved,setApproved]=useState(false);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [uncertain,setUncertain]=useState(false);
 const abort=useRef<AbortController|null>(null);const review=useRef<HTMLElement>(null);const results=useRef<HTMLElement>(null);
 useEffect(()=>()=>abort.current?.abort(),[]);
 const stale=!!plan&&signature!==JSON.stringify([request,student]);
 async function planning(){if(busy)return;setBusy('Planning and validating request…');setError('');setNotice('');setApproved(false);const controller=new AbortController();abort.current=controller;try{if(plan)await client.discardAssistant(plan.handle);if(controller.signal.aborted)return;setPlan(null);setReport(null);setUncertain(false);const p=await client.planAssistant(request,student||null,controller.signal);const next=await client.previewAssistant(p.handle,controller.signal);if(!controller.signal.aborted){setPlan(next);setSignature(JSON.stringify([request,student]));setPlannedStudent(student);requestAnimationFrame(()=>review.current?.focus());}}catch(e){if(!controller.signal.aborted)setError(safe(e));}finally{if(!controller.signal.aborted)setBusy('');}}
 async function execute(retry=false){if(!plan||stale||!approved||busy||uncertain)return;setBusy(retry?'Retrying failed actions…':'Executing confirmed plan…');setError('');setNotice('');const controller=new AbortController();abort.current=controller;try{await client.executeAssistant(plan.handle,retry,controller.signal);const outcome=await client.assistantResults(plan.handle,controller.signal);if(!controller.signal.aborted){setReport(outcome);setApproved(false);requestAnimationFrame(()=>results.current?.focus());}}catch(e){if(!controller.signal.aborted){setError(safe(e));setUncertain(true);}}finally{if(!controller.signal.aborted)setBusy('');}}
 async function recover(){if(!plan||busy)return;setBusy('Checking stored execution results…');setError('');try{setReport(await client.assistantResults(plan.handle));setUncertain(false);}catch(e){setError(safe(e));}finally{setBusy('');}}
 function stop(){abort.current?.abort();setUncertain(!!plan);setBusy('');setNotice('Stopped browser waiting. Backend inference/execution was not cancelled. Check stored execution results before retrying.');}
 async function discard(){if(!plan||busy)return;setBusy('Discarding plan…');setError('');try{await client.discardAssistant(plan.handle);setPlan(null);setReport(null);setApproved(false);setUncertain(false);setNotice('Plan discarded. Already opened studio drafts remain in their dedicated workspaces.');}catch(e){setError(safe(e));}finally{setBusy('');}}
 async function handoff(action_id:string,destination:'ASSESSMENT'|'DOCUMENT'|'KNOWLEDGE_SCOPE'){if(!plan||busy)return;setBusy('Opening protected studio draft…');setError('');try{const h=await client.handoffAssistant(plan.handle,action_id,destination);router.push(`${destination==='ASSESSMENT'?'/assessment':destination==='DOCUMENT'?'/documents':'/knowledge'}?workspace=${encodeURIComponent(h.handle)}`);}catch(e){setError(safe(e));}finally{setBusy('');}}
 return <><PageHeading eyebrow="Professor-controlled orchestration" title="Smart Assistant" description="Describe a task, review a validated plan and explicitly approve execution. EduAgent coordinates existing authorized services; it cannot run arbitrary commands or contact external systems."/>
 <p className="footnote">Session-only plans and results. No persistent conversation history. Student records stay local and never enter AI prompts. Generated content remains subject to professor review in its studio.</p>
 {error&&<ErrorNotice message={error}/>} {notice&&<p role="status">{notice}</p>} {busy&&<Loading label={busy}/>}
 <section className="panel"><h2>Your request</h2><form onSubmit={e=>{e.preventDefault();void planning();}}><label className="field" htmlFor="assistant-request">Professor request</label><textarea id="assistant-request" rows={4} maxLength={4000} required value={request} disabled={!!busy} onChange={e=>{setRequest(e.target.value);setApproved(false);}}/><div className="assistant-suggestions" aria-label="Supported starter requests">{['Ask my course material about PCA.','Create a quiz from my selected course and unit.','Draft a notice for a seminar.','Open my recent documents.','Show students with concern.'].map(s=><button type="button" className="button secondary" disabled={!!busy} key={s} onClick={()=>{setRequest(s);setApproved(false);}}>{s}</button>)}</div>
 <label className="field" htmlFor="assistant-dataset">Temporary student dataset (optional)</label><select id="assistant-dataset" disabled={!!busy||datasets.loading} value={student} onChange={e=>{setStudent(e.target.value);setApproved(false);}}><option value="">No student dataset attached</option>{datasets.data?.map((d,i)=><option key={d.handle} value={d.handle}>Temporary dataset {i+1}</option>)}</select><p className="field-hint">Upload in Student Analytics first. Attaching a dataset supplies only availability to planning; supported student operations are deterministic.</p>{datasets.error&&<ErrorNotice message="Cannot inspect temporary workspace availability." retry={datasets.retry}/>}
 <button className="button primary" disabled={!!busy||!request.trim()}>Review plan</button></form></section>
 {plan&&<section className="panel assistant-plan" ref={review} tabIndex={-1} aria-label="Plan preview"><div className="section-heading"><h2>{plan.unsupported?'Unsupported request':plan.valid?'Plan validated':'Clarification required'}</h2><button className="button secondary" disabled={!!busy} onClick={()=>void discard()}>Discard plan</button></div>
 {plan.unsupported?<p>This operation is unavailable. Use a supported academic workflow. No actions were executed.</p>:<><p>Maximum five allowlisted actions. All execution is explicit. Dependencies can transfer only the supported assessment summary into a document.</p><ol className="assistant-steps">{plan.actions.map((a,i)=><li key={a.action_id}><h3>Step {i+1}: {labels[a.action_type]}</h3>{scope(a.parameters)&&<p>Scope: {scope(a.parameters)}</p>}<p>{a.depends_on.length?`Requires completion of step ${a.depends_on.map(d=>plan.actions.findIndex(v=>v.action_id===d)+1).join(', ')}.`:'Independent action.'}</p><p>{report?report.results.find(o=>o.action_id===a.action_id)?.status??'Pending':busy.includes('Executing')||busy.includes('Retrying')?'Execution running; step status pending':approved?'Approved; pending execution':'Awaiting explicit professor approval'} · {a.action_type==='CREATE_ASSESSMENT'?'Assessment Studio review':a.action_type==='CREATE_DOCUMENT'?'Document Studio review':a.action_type==='ANALYZE_STUDENTS'?'Local Student Analytics':a.action_type==='ASK_KNOWLEDGE'?'Grounded answer or no-evidence result':'Workspace navigation'}</p>{plan.clarifications.filter(c=>c.action_id===a.action_id).map(c=><p key={c.action_id} className="notice">Provide: {c.missing_fields.map(f=>fields[f]??'Required information').join(', ')}. Update your request and review a new plan.</p>)}</li>)}</ol>
 {stale&&<p role="status">Request or dataset selection changed. Review a new plan before execution.</p>}
 {plan.valid&&!report&&<><label className="check-label"><input type="checkbox" checked={approved} disabled={!!busy||stale||uncertain} onChange={e=>setApproved(e.target.checked)}/>I approve this exact plan for execution.</label><button className="button primary" disabled={!approved||!!busy||stale||uncertain} onClick={()=>void execute()}>Execute approved plan</button></>}
 </>}{uncertain&&<button className="button secondary" disabled={!!busy} onClick={()=>void recover()}>Check execution results</button>}</section>}
 {report&&plan&&<section className="panel assistant-results" ref={results} tabIndex={-1} aria-label="Execution results"><h2>{report.status==='completed'?'Completed':report.status==='partial_failure'?'Partial failure':'Execution failed'}</h2><ol className="assistant-steps">{report.results.map((o,i)=><li key={o.action_id}><h3>Step {i+1}: {labels[o.type]} — {o.status}</h3><p>{o.summary}</p>{o.status==='failed'&&<p>The service could not produce an authorized valid result. Review the request, available academic evidence and local service availability.</p>}{o.status==='blocked'&&<p>A required earlier step failed. This action was not executed.</p>}{o.status==='completed'&&<>{o.answer!==null&&<><p className="badge">{o.grounded?'Grounded answer available':'Insufficient matching material'}</p><div className="assistant-answer">{o.answer}</div>{o.sources.length>0&&<ul aria-label="Answer sources">{o.sources.map((s,n)=><li key={n}>{s}</li>)}</ul>}</>}{o.student_count!==null&&<p>{o.student_count} students in the requested local view. Individual records remain in Student Analytics.</p>}{o.type==='CREATE_ASSESSMENT'||o.type==='CREATE_DOCUMENT'||o.type==='ASK_KNOWLEDGE'?<button className="button secondary" disabled={!!busy} onClick={()=>void handoff(o.action_id,o.type==='CREATE_ASSESSMENT'?'ASSESSMENT':o.type==='CREATE_DOCUMENT'?'DOCUMENT':'KNOWLEDGE_SCOPE')}>Open in {o.type==='CREATE_ASSESSMENT'?'Assessment Studio':o.type==='CREATE_DOCUMENT'?'Document Studio':'Knowledge'}</button>:o.type==='ANALYZE_STUDENTS'&&plannedStudent?<Link className="button secondary" href={`/students?workspace=${encodeURIComponent(plannedStudent)}&view=${encodeURIComponent(String(plan.actions.find(a=>a.action_id===o.action_id)?.parameters.view??'All'))}`}>Open in Student Analytics</Link>:o.destination&&destinations.has(o.destination)?<Link className="button secondary" href={o.destination}>Open workspace</Link>:null}</>}</li>)}</ol>{report.status!=='completed'&&<><label className="check-label"><input type="checkbox" checked={approved} disabled={!!busy||stale||uncertain} onChange={e=>setApproved(e.target.checked)}/>I approve retrying failed safe actions.</label><button className="button secondary" disabled={!approved||!!busy||stale||uncertain} onClick={()=>void execute(true)}>Retry failed actions</button><p>Completed actions are retained and reauthorized. Retry is explicit; no silent generation retry.</p></>}</section>}
 {busy&&<button className="text-button" onClick={stop}>Stop waiting</button>}
 </>;
}
