"use client";
import { useCallback } from "react";
import Link from "next/link";
import { ArrowUpRight, BookOpen, FolderOpen, FileText, ArrowRight } from "lucide-react";
import { useAuth } from "@/features/auth";
import { useResource } from "@/features/use-resource";
import { PageHeading, Loading, ErrorNotice, Empty } from "@/components/states";
export function AIConfiguration() {
  const { client } = useAuth(); const load = useCallback((signal: AbortSignal) => client.status(signal), [client]); const status = useResource(load);
  return <section className="status-strip" aria-label="AI configuration"><BookOpen size={18} aria-hidden="true"/><div>{status.loading ? <span role="status">Checking AI configuration…</span> : status.error ? <><strong>AI status unavailable</strong><button className="text-button" onClick={status.retry}>Retry</button></> : status.data ? <><strong>Course-grounded answers configured</strong><span>Preferred model: {status.data.preferred_model}. Service availability is checked when you ask a question.</span></> : null}</div></section>;
}
export function DashboardPage() {
  const { client, session } = useAuth(); const load = useCallback((signal: AbortSignal) => client.dashboard(signal), [client]); const view = useResource(load);
  return <><PageHeading eyebrow="Your academic workspace" title="A clear view of your work" description={session.status === "authenticated" ? `Welcome, ${session.professor.display_name}. Browse your materials and continue with your course knowledge.` : "Your professor workspace."}><Link href="/knowledge" className="button primary">Ask a question <ArrowUpRight size={16} aria-hidden="true"/></Link></PageHeading>
    {view.loading ? <Loading label="Loading your materials, documents and activity…"/> : view.error ? <ErrorNotice message={view.error} retry={view.retry}/> : view.data && <>
    <section className="summary-grid" aria-label="Workspace summary"><div><BookOpen size={19} aria-hidden="true"/><strong>{view.data.material_count}</strong><Link href="/library">Registered materials</Link></div><div><FolderOpen size={19} aria-hidden="true"/><strong>{view.data.courses.length}</strong><Link href="/courses">Courses with materials</Link></div><div><FileText size={19} aria-hidden="true"/><strong>{view.data.saved_drafts.length}</strong><span>Saved documents</span></div></section>
    <div className="dashboard-grid"><section className="panel"><div className="section-heading"><h2>Course materials</h2><Link href="/library">View library <ArrowRight size={14} aria-hidden="true"/></Link></div>{view.data.materials.length ? <ul className="resource-list">{view.data.materials.slice(0,5).map((m) => <li key={m.material_id}><span className="document-icon"><FileText size={18} aria-hidden="true"/></span><div><strong>{m.filename}</strong><p>{m.course} · {m.subject} · {m.unit}</p></div><Link aria-label={`Ask about ${m.filename}`} href={`/knowledge?material=${encodeURIComponent(m.material_id)}`} className="icon-button"><ArrowUpRight size={18}/></Link></li>)}</ul> : <Empty title="No materials uploaded yet" detail="Your authorized course materials will appear here. Upload academic material to begin building your course knowledge." href="/library" action="Open material library"/>}</section>
    <section className="panel"><div className="section-heading"><h2>Recent activity</h2></div>{view.data.activity.length ? <ul className="activity-list">{view.data.activity.map((a,i) => <li key={`${a.timestamp}-${i}`}><span className="activity-dot" aria-hidden="true"/><div><strong>{a.action}</strong><time dateTime={a.timestamp}>{new Date(a.timestamp).toLocaleString(undefined,{dateStyle:"medium",timeStyle:"short"})}</time></div></li>)}</ul> : <Empty title="No recent activity" detail="Safe activity recorded by your workspace will appear here."/>}</section></div>
    <section className="panel"><div className="section-heading"><h2>Saved documents</h2><span className="badge">Document Studio · upcoming</span></div>{view.data.saved_drafts.length ? <div className="table-scroll"><table><caption className="sr-only">Saved document metadata</caption><thead><tr><th>Document</th><th>Status</th><th>Last updated</th></tr></thead><tbody>{view.data.saved_drafts.slice(0,5).map((d,i) => <tr key={d.document_id}><td>Saved academic document {i+1}</td><td><span className="badge">{d.status}</span></td><td>{new Date(d.updated_at).toLocaleDateString()}</td></tr>)}</tbody></table></div> : <Empty title="No saved documents yet" detail="Documents saved in the backend will appear here. Drafting is available in the Streamlit reference workspace."/>}</section>
    <section className="quick-actions" aria-label="Quick actions"><Link href="/knowledge">Ask Knowledge <ArrowUpRight size={16}/></Link><Link href="/library">Browse materials <ArrowUpRight size={16}/></Link><Link href="/library/upload">Upload material <ArrowUpRight size={16}/></Link><Link href="/assessment">Create assessment <ArrowUpRight size={16}/></Link>{[["Draft document","documents"],["Analyze students","students"],["Smart Assistant","assistant"]].map(([label,slug]) => <Link key={slug} href={`/workspace/${slug}`}>{label}<span className="badge">Upcoming</span></Link>)}</section></>}
    <AIConfiguration/></>;
}
