"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { BookOpen, ArrowRight, CheckCircle2 } from "lucide-react";
import { useAuth } from "@/features/auth";
import { useResource } from "@/features/use-resource";
import { APIError } from "@/lib/api";
import { PageHeading, Loading, ErrorNotice, Empty } from "@/components/states";
import type { Answer, Scope } from "@/types/api";
export function KnowledgePage(){const params=useSearchParams();return <KnowledgeView key={params.toString()}/>;}
function KnowledgeView() {
  const { client } = useAuth(); const params = useSearchParams(); const initialMaterial=params.get("material") ?? "";
  const load=useCallback((signal:AbortSignal)=>client.materials(signal),[client]);const library=useResource(load);
  const [question,setQuestion]=useState(""); const [scope,setScope]=useState<Scope>({material_id:initialMaterial,...Object.fromEntries((["course","semester","subject","unit"] as const).map(k=>[k,params.get(k)??""]))}); const [response,setResponse]=useState<{value:Answer;question:string;scope:Scope}|null>(null);
  const [pending,setPending]=useState(false); const [error,setError]=useState<string|null>(null); const [notice,setNotice]=useState<string|null>(null);const request=useRef<AbortController|null>(null);const resultRef=useRef<HTMLElement|null>(null);
  useEffect(()=>()=>request.current?.abort(),[]);
  const incoming=params.get('workspace');const [handoffPending,setHandoffPending]=useState(!!incoming);const [handoffFailed,setHandoffFailed]=useState(false);
  useEffect(()=>{if(!incoming)return;const abort=new AbortController();client.knowledgeScope(incoming,abort.signal).then(a=>{if(!abort.signal.aborted){setQuestion(a.question);setScope(a.filters);}}).catch(e=>{if(!abort.signal.aborted){setHandoffFailed(true);setError(e instanceof APIError?e.message:'Cannot load this academic scope.');}}).finally(()=>{if(!abort.signal.aborted)setHandoffPending(false);});return()=>abort.abort();},[incoming,client]);
  const scoped=library.data?.filter((m)=>(!scope.course||m.course===scope.course)&&(!scope.semester||m.semester===scope.semester)&&(!scope.subject||m.subject===scope.subject)&&(!scope.unit||m.unit===scope.unit))??[];
  const values=(key: "course"|"semester"|"subject"|"unit")=>[...new Set((library.data??[]).filter((m)=>(key==="course"||!scope.course||m.course===scope.course)&&(key==="course"||key==="semester"||!scope.semester||m.semester===scope.semester)&&(key!=="unit"||!scope.subject||m.subject===scope.subject)).map((m)=>m[key]))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));
  const change=(key: "course"|"semester"|"subject"|"unit",value:string)=>{const order=["course","semester","subject","unit","material_id"] as const; const index=order.indexOf(key);setScope(Object.fromEntries(order.map((k,i)=>[k,i<index?scope[k]??"":i===index?value:""])));};
  const submit=async()=>{
    if (!question.trim() || pending || handoffPending || handoffFailed) return;request.current?.abort();const controller=new AbortController();request.current=controller;setPending(true);setError(null);setNotice(null);setResponse(null);
    const asked=question.trim();const filters=Object.fromEntries(Object.entries(scope).filter(([,v])=>v));
    try { const value=await client.answer({question:asked,filters},controller.signal);if(!controller.signal.aborted){setResponse({value,question:asked,scope:filters});requestAnimationFrame(()=>resultRef.current?.focus());} }
    catch(e){if(!controller.signal.aborted)setError(e instanceof APIError?e.message:"Cannot complete this question. Try again later.");}
    finally { if(!controller.signal.aborted)setPending(false); }
  };
  const stop=()=>{request.current?.abort();setPending(false);setNotice("Stopped waiting. The synchronous backend may still finish this request; no server cancellation was sent.");};
  if(handoffPending)return <Loading label="Loading your selected academic scope…"/>;
  if(handoffFailed)return <Empty title="Knowledge scope unavailable" detail="The handoff may have expired or become unauthorized. Choose a new scope explicitly." href="/knowledge" action="Start a new question"/>;
  return <><PageHeading eyebrow="Knowledge" title="Ask your course material" description="Get a grounded answer from authorized academic materials, with source references for professor review."/>
    <section className="panel question-panel" aria-labelledby="question-heading"><h2 id="question-heading">Academic question</h2><form onSubmit={(e)=>{e.preventDefault();void submit();}}><div className="field"><label htmlFor="academic-question">What would you like to understand?</label><textarea id="academic-question" required maxLength={4000} rows={4} placeholder="Ask a specific question about your course material…" value={question} onChange={(e)=>setQuestion(e.target.value)} disabled={pending}/><span className="field-hint">Answers use retrieved material. They still require your academic review.</span></div>
    <p className="field-hint">Current scope: {library.data?.find(m=>m.material_id===scope.material_id)?.filename || Object.entries(scope).filter(([k,v])=>k!=="material_id"&&v).map(([,v])=>v).join(" → ") || "All authorized materials"}</p><button className="text-button" type="button" disabled={pending} onClick={()=>setScope({})}>Clear scope</button><fieldset className="scope-controls" disabled={pending||library.loading}><legend>Search scope</legend>{(["course","semester","subject","unit"] as const).map((key)=><div className="field" key={key}><label htmlFor={`scope-${key}`}>{key.charAt(0).toUpperCase()+key.slice(1)}</label><select id={`scope-${key}`} value={scope[key]??""} onChange={(e)=>change(key,e.target.value)}><option value="">All {key}s</option>{values(key).map((v)=><option key={v}>{v}</option>)}</select></div>)}<div className="field material-scope"><label htmlFor="scope-material">Material</label><select id="scope-material" value={scope.material_id??""} onChange={(e)=>setScope({...scope,material_id:e.target.value})}><option value="">All materials in this scope</option>{scoped.map((m)=><option key={m.material_id} value={m.material_id}>{m.filename}</option>)}{initialMaterial&&!library.data?.some((m)=>m.material_id===initialMaterial)&&<option value={initialMaterial}>Selected material (access checked by backend)</option>}</select></div></fieldset>
    {library.loading&&<p className="field-hint" role="status">Loading available scope options…</p>}{library.error&&<ErrorNotice message={library.error} retry={library.retry}/>}<div className="form-footer"><p><BookOpen size={16} aria-hidden="true"/>Authorized material only</p><button className="button primary" disabled={pending||!question.trim()} type="submit">{pending?"Finding an answer…":"Ask question"}<ArrowRight size={16} aria-hidden="true"/></button></div></form></section>
    {pending&&<section className="panel" aria-busy="true"><Loading label="Retrieving course evidence and preparing your answer…"/><button className="text-button" onClick={stop}>Stop waiting</button></section>}{notice&&<p className="notice" role="status">{notice}</p>}{error&&<ErrorNotice message={error} retry={()=>{void submit();}}/>}
    {response?<section className="panel answer-panel" ref={resultRef} tabIndex={-1} aria-labelledby="answer-heading"><div className="section-heading"><h2 id="answer-heading">{response.value.grounded?"Grounded answer":"Insufficient matching material"}</h2><span className={`badge ${response.value.grounded?"success":"warning"}`}><CheckCircle2 size={14} aria-hidden="true"/>{response.value.grounded?"Material-grounded":"No evidence"}</span></div><p className="asked-question">{response.question}</p><p className="field-hint">Scope: {Object.entries(response.scope).filter(([k])=>k!=="material_id").map(([,v])=>v).join(" / ")||"All authorized course materials"}{response.scope.material_id?" · selected material":""}</p><div className="answer-text">{response.value.answer}</div>{response.value.grounded?<><h3 className="sources-heading">Source references</h3><ul className="source-list">{response.value.sources.map((s,i)=>{const m=library.data?.find((m)=>m.material_id===s.material_id);return <li key={`${s.material_id}-${i}`}><BookOpen size={17} aria-hidden="true"/><div><strong>{s.source}</strong>{m&&<p>{m.course} · {m.semester} · {m.subject} · {m.unit}</p>}</div></li>;})}</ul><p className="footnote">Grounding indicates material support, not a guarantee of factual accuracy.</p></>:<p className="footnote">EduAgent couldn’t find enough evidence in the selected academic material. Try a more specific question or change scope. <Link href="/library/upload">Upload relevant material</Link></p>}</section>:!pending&&!error&&!notice&&<Empty title="Start with a course question" detail="Your answer and academic source references will appear here. No conversation history is stored by this page."/>}</>;
}
