'use client';
import { useCallback,useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { useAuth } from '@/features/auth';
import { useResource } from '@/features/use-resource';
import { PageHeading,Loading,ErrorNotice,Empty } from '@/components/states';
import { levels,options,scopeURL } from '@/lib/academic';
import type { Scope } from '@/types/api';
export function LibraryPage(){const params=useSearchParams();return <LibraryView key={params.toString()}/>;}
function LibraryView(){const {client}=useAuth();const params=useSearchParams();const load=useCallback((signal:AbortSignal)=>client.materials(signal),[client]);const view=useResource(load);const [search,setSearch]=useState('');const [scope,setScope]=useState<Scope>({course:params.get('course')??''});const [page,setPage]=useState(1);
 const materials=(view.data??[]).filter(m=>levels.every(k=>!scope[k]||scope[k]===m[k])&&`${m.filename} ${m.course} ${m.semester} ${m.subject} ${m.unit}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a,b)=>b.created_at.localeCompare(a.created_at)||a.material_id.localeCompare(b.material_id));const pages=Math.max(1,Math.ceil(materials.length/20));const activePage=Math.min(page,pages);const visible=materials.slice((activePage-1)*20,activePage*20);
 return <><PageHeading eyebrow="Academic foundation" title="Your material library" description="Organize the authorized academic knowledge available to EduAgent."><Link className="button primary" href="/library/upload">Upload material</Link></PageHeading><section className="panel"><div className="field"><label htmlFor="material-search">Find a material</label><input id="material-search" type="search" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search filename or academic placement"/></div><fieldset className="scope-controls"><legend>Academic filters</legend>{levels.map((k,index)=><div className="field" key={k}><label htmlFor={`library-${k}`}>{k.charAt(0).toUpperCase()+k.slice(1)}</label><select id={`library-${k}`} value={scope[k]??''} onChange={e=>{setScope(Object.fromEntries(levels.map((key,i)=>[key,i<index?scope[key]??'':i===index?e.target.value:''])));setPage(1);}}><option value="">All {k}s</option>{options(view.data??[],scope,k).map(v=><option key={v}>{v}</option>)}</select></div>)}</fieldset>{view.loading?<Loading label="Loading your authorized material library…"/>:view.error?<ErrorNotice message={view.error} retry={view.retry}/>:!view.data?.length?<Empty title="No materials uploaded yet" detail="Add your first academic file and assign its course hierarchy." href="/library/upload" action="Upload material"/>:!materials.length?<Empty title="No materials match this view" detail="Try another academic scope or search term."/>:<><p className="field-hint">{materials.length} materials · page {activePage} of {pages}</p><div className="table-scroll"><table className="material-table"><caption className="sr-only">Authorized academic material library</caption><thead><tr><th>Material</th><th>Course / Semester</th><th>Subject / Unit</th><th>Added</th><th>Actions</th></tr></thead><tbody>{visible.map(m=><tr key={m.material_id}><td><Link href={`/library/${encodeURIComponent(m.material_id)}`}><strong>{m.filename}</strong></Link></td><td>{m.course}<small>{m.semester}</small></td><td>{m.subject}<small>{m.unit}</small></td><td>{new Date(m.created_at).toLocaleDateString()}</td><td><Link href={scopeURL({material_id:m.material_id})}>Ask<span className="sr-only"> about {m.filename}</span></Link></td></tr>)}</tbody></table></div><div className="pagination" aria-label="Material pages"><button className="button" disabled={activePage===1} onClick={()=>setPage(activePage-1)}>Previous</button><button className="button" disabled={activePage===pages} onClick={()=>setPage(activePage+1)}>Next</button></div></>}</section></>;}
