"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { GraduationCap, ArrowRight, ShieldCheck } from "lucide-react";
import { useAuth } from "@/features/auth";
import { ErrorNotice } from "@/components/states";
import { APIError } from "@/lib/api";
export function LoginPage({ enabled, aliases }: { enabled: boolean; aliases: string[] }) {
  const auth=useAuth();const router=useRouter();const [alias,setAlias]=useState(aliases[0]??"");const [pending,setPending]=useState(false);const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(auth.ready&&auth.session.status==="authenticated")router.replace("/home");},[auth.ready,auth.session.status,router]);
  const signIn=async()=>{setPending(true);setError(null);try{await auth.login(alias);}catch(e){setError(e instanceof APIError?e.message:"Cannot sign in. Check development configuration.");}finally{setPending(false);}};
  return <main className="login-page"><section className="login-card"><div className="login-brand"><GraduationCap size={32} aria-hidden="true"/><strong>EduAgent</strong></div><p className="eyebrow">Higher education · Professor workspace</p><h1>Your materials.<br/>Your academic workspace.</h1><p className="lede">Course-grounded knowledge and a clear view of your work, in one focused workspace.</p>{enabled?<><div className="development-warning"><ShieldCheck size={20} aria-hidden="true"/><div><strong>Development authentication only</strong><p>Choose a seeded development identity. This is not institutional sign-in.</p></div></div>{aliases.length?<form onSubmit={(e)=>{e.preventDefault();void signIn();}}><div className="field"><label htmlFor="development-identity">Development professor</label><select id="development-identity" value={alias} onChange={(e)=>setAlias(e.target.value)} disabled={pending}>{aliases.map((a)=><option key={a} value={a}>{a}</option>)}</select></div><button className="button primary" type="submit" disabled={pending}>{pending?"Verifying identity…":"Open workspace"}<ArrowRight size={17} aria-hidden="true"/></button></form>:<p role="status">No development identities configured. Follow the local setup instructions.</p>}</>:<div className="development-warning"><div><strong>Sign-in is not configured</strong><p>Development login is disabled. Institutional authentication has not been connected yet.</p></div></div>}{error&&<ErrorNotice message={error}/>}<p className="login-note">Your identity and material access are verified by the backend. Session credentials stay in an HTTP-only cookie.</p></section><aside className="login-aside" aria-label="Workspace capabilities"><p className="eyebrow">A focused academic environment</p><h2>From course material<br/>to useful understanding.</h2><ul><li><strong>Grounded knowledge</strong><p>Answers supported by your authorized academic materials.</p></li><li><strong>A connected library</strong><p>Course → Semester → Subject → Unit → Material.</p></li><li><strong>A careful migration</strong><p>Studio workflows remain available in Streamlit while the web workspace grows.</p></li></ul></aside></main>;
}
