'use client';
import { useCallback,useRef,useState } from 'react';
import Link from 'next/link';
import { useAuth } from '@/features/auth';
import { useResource } from '@/features/use-resource';
import { APIError } from '@/lib/api';
import { PageHeading,Loading,ErrorNotice,Empty } from '@/components/states';
import { HierarchyFields } from '@/components/hierarchy';
import { courseURL,levels,normalizeHierarchy,scopeURL,assessmentURL } from '@/lib/academic';
import type { Hierarchy,Material } from '@/types/api';
const empty:Hierarchy={course:'',semester:'',subject:'',unit:''};
const failure=(e:unknown)=>e instanceof APIError?e.message:'Material operation could not complete. Check the connection before retrying.';
export function UploadPage(){
 const {client}=useAuth();const load=useCallback((signal:AbortSignal)=>client.materials(signal),[client]);const library=useResource(load);
 const [hierarchy,setHierarchy]=useState(empty);const [file,setFile]=useState<File|null>(null);const [pending,setPending]=useState(false);const [error,setError]=useState<string|null>(null);const [saved,setSaved]=useState<Material|null>(null);
 async function submit(){if(!file||pending)return;setError(null);setSaved(null);const ext=file.name.split('.').at(-1)?.toLowerCase();if(!['pdf','png','jpg','jpeg'].includes(ext??'')){setError('Choose a PDF, PNG, JPG or JPEG material.');return;}if(file.size>10*1024*1024){setError('This upload exceeds the API file limit of 10 MiB.');return;}if(!file.size){setError('Choose a non-empty material file.');return;}
 setPending(true);try{const normalized=normalizeHierarchy(hierarchy,library.data??[]);const result=await client.upload(file,normalized);if(result.success&&result.material){setSaved(result.material);library.retry();}else setError(result.duplicate?'This exact file content is already registered. No additional material was uploaded. Review your library.':'Material was not registered. Check the file format, readable content and local OCR/storage availability before retrying.');}catch(e){setError(failure(e));}finally{setPending(false);}}
 return <><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/library">Material library</Link> / Upload</nav><PageHeading eyebrow="Academic knowledge" title="Upload material" description="Place a PDF or supported image in your course hierarchy. Image text is extracted with local OCR."/><section className="panel"><form aria-describedby={error?"upload-error":undefined} onSubmit={e=>{e.preventDefault();void submit();}}><div className="field"><label htmlFor="material-file">Academic file</label><input id="material-file" type="file" accept=".pdf,.png,.jpg,.jpeg" disabled={pending} required aria-describedby="upload-help" onChange={e=>{setFile(e.target.files?.[0]??null);setError(null);setSaved(null);}}/><p id="upload-help" className="field-hint">PDF, PNG, JPG or JPEG. API limit: 10 MiB; configured backend limits may be lower. File contents are validated by the backend.</p>{file&&<p>{file.name} · {file.name.split('.').at(-1)?.toUpperCase()} · {(file.size/1024).toFixed(1)} KiB</p>}</div><HierarchyFields value={hierarchy} onChange={setHierarchy} materials={library.data??[]} prefix="upload" disabled={pending}/><p className="footnote">New uploads are private to your professor account. Select an existing academic value or enter a new one.</p><button className="button primary" disabled={pending||!file} type="submit">{pending?'Processing material…':'Upload material'}</button>{pending&&<p role="status">Processing material. Extraction and indexing may take time; progress percentages are not available.</p>}</form>{library.error&&<ErrorNotice message={library.error} retry={library.retry}/>} {error&&<div id="upload-error"><ErrorNotice message={error}/></div>} {saved&&<div className="notice" role="status"><strong>Material registered: {saved.filename}</strong><p>{saved.course} · {saved.semester} · {saved.subject} · {saved.unit}</p><Link href={`/library/${encodeURIComponent(saved.material_id)}`}>Open material</Link> · <Link href={scopeURL({material_id:saved.material_id})}>Ask about this material</Link></div>}</section></>;
}
export function MaterialPage({identity}:{identity:string}){
 const {client}=useAuth();const load=useCallback((signal:AbortSignal)=>client.material(identity,signal),[client,identity]);const view=useResource(load);const all=useCallback((signal:AbortSignal)=>client.materials(signal),[client]);const library=useResource(all);const [edit,setEdit]=useState<Hierarchy|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);const [deleted,setDeleted]=useState(false);const dialog=useRef<HTMLDialogElement>(null);
 async function update(){if(!edit||busy)return;setBusy(true);setError(null);setNotice(null);try{const normalized=normalizeHierarchy(edit,library.data??[]);const result=await client.editMaterial(identity,normalized);if(!result.success){setError('Academic placement was not updated completely. Keep this material under review and check local storage before retrying.');view.retry();return;}setEdit(null);setNotice('Academic placement updated. Course and Knowledge views now use the saved hierarchy.');view.retry();library.retry();}catch(e){setError(failure(e));}finally{setBusy(false);}}
 async function remove(){if(busy)return;setBusy(true);setError(null);setNotice(null);try{const result=await client.deleteMaterial(identity);dialog.current?.close();if(result.success){setDeleted(true);setNotice('Material and its indexed knowledge were removed.');}else{setError('Deletion did not complete across all managed storage. Do not assume the material is removed. Check local storage and refresh before retrying.');view.retry();}}catch(e){dialog.current?.close();setError(failure(e));}finally{setBusy(false);}}
 const m=view.data;return <><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/courses">Courses</Link>{m&&<> / <Link href={courseURL(m.course)}>{m.course}</Link></>} / <Link href="/library">Materials</Link>{m&&<> / {m.filename}</>}</nav><PageHeading eyebrow="Academic material" title={deleted?'Material removed':m?.filename??'Material details'} description="Inspect academic placement and manage this material through protected backend operations."/>{notice&&<p className="notice" role="status">{notice}</p>}{error&&<ErrorNotice message={error}/>} {deleted?<Empty title="This material is no longer registered" detail="Return to the library to review your remaining materials." href="/library" action="Open material library"/>:view.loading?<Loading label="Loading authorized material…"/>:view.error?<ErrorNotice message={view.error} retry={view.retry}/>:m&&<section className="panel"><h2>Academic placement</h2><dl className="metadata-grid">{levels.map(k=><div key={k}><dt>{k.charAt(0).toUpperCase()+k.slice(1)}</dt><dd>{m[k]}</dd></div>)}<div><dt>Material type</dt><dd>{m.filename.split('.').at(-1)?.toUpperCase()}</dd></div><div><dt>Uploaded</dt><dd>{new Date(m.created_at).toLocaleString()}</dd></div></dl><p className="footnote">Visibility: {{PRIVATE:"Private to its owner",COURSE:"Shared with authorized course members",DEPARTMENT:"Shared within its department",INSTITUTE:"Shared within its institution"}[m.visibility]}. New uploads are private. Sharing changes remain in the reference workflow.</p><div className="quick-actions"><Link href={scopeURL({material_id:identity})}>Ask about this material</Link><Link href={assessmentURL({material_id:identity})}>Create quiz from this material</Link>{m.can_manage&&<><button className="button" disabled={busy} onClick={()=>{setEdit({course:m.course,semester:m.semester,subject:m.subject,unit:m.unit});setError(null);}}>Edit academic placement</button><button className="button danger" disabled={busy} onClick={()=>dialog.current?.showModal()}>Delete material</button></>}</div>{edit&&<form onSubmit={e=>{e.preventDefault();void update();}}><HierarchyFields value={edit} onChange={setEdit} materials={library.data??[]} prefix="edit" disabled={busy}/><button className="button primary" disabled={busy}>Save placement</button> <button className="button" type="button" disabled={busy} onClick={()=>setEdit(null)}>Cancel editing</button></form>}</section>}
 <dialog className="confirmation-dialog" ref={dialog} aria-labelledby="delete-title" aria-describedby="delete-description" onCancel={e=>{if(busy)e.preventDefault();}}><h2 id="delete-title">Delete material?</h2><p id="delete-description"><strong>{m?.filename}</strong> and its indexed knowledge will be removed. This cannot be undone.</p><div className="quick-actions"><button className="button" autoFocus disabled={busy} onClick={()=>dialog.current?.close()}>Keep material</button><button className="button danger" disabled={busy} onClick={()=>{void remove();}}>{busy?'Deleting…':'Confirm deletion'}</button></div></dialog></>;
}
