"use client";
import {useEffect,useRef,useState} from "react";
import {useSearchParams} from "next/navigation";
import {useAuth} from "@/features/auth";
import {APIError} from "@/lib/api";
import {PageHeading,Loading,ErrorNotice} from "@/components/states";
import type {Analysis,Detail,Filters,Mapping,Normalized,Preview,Row} from "@/types/students";
const initialFilters:Filters={view:"All",search:"",marks_threshold:50,attendance_threshold:70};
function value(v:unknown):string{return v===null||v===undefined?"Missing":Array.isArray(v)?v.join(", "):String(v);}
const issueLabels:Record<string,string>={invalid_mark:"Invalid marks",invalid_attendance:"Invalid attendance",duplicate_id:"Duplicate identifier",duplicate_identity:"Duplicate identity",missing_mark:"Missing marks",missing_attendance:"Missing attendance",missing_id:"Missing identifier",missing_name:"Missing name",invalid_history:"Invalid student history",invalid_assessment_number:"Invalid assessment number",inconsistent_name:"Inconsistent name",summary_row:"Summary row excluded",header_disambiguated:"Review duplicate or blank headers"};
export function StudentAnalyticsPage(){
 const params=useSearchParams();const incoming=params.get("workspace");const incomingView=params.get("view")??"All";
 const auth=useAuth();const {client}=auth;
 const [book,setBook]=useState<{handle:string;sheets:string[]}|null>(null);const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState<Preview|null>(null);const [sheet,setSheet]=useState("");const [header,setHeader]=useState(1);
 const [mapping,setMapping]=useState<Mapping|null>(null);const [dataset,setDataset]=useState<Normalized|null>(null);const [analysis,setAnalysis]=useState<Analysis|null>(null);const [all,setAll]=useState<Row[]>([]);const [detail,setDetail]=useState<Detail|null>(null);
 const [filters,setFilters]=useState<Filters>(initialFilters);const [applied,setApplied]=useState<Filters>(initialFilters);const [sort,setSort]=useState("student_id");const [page,setPage]=useState(0);const [busy,setBusy]=useState(incoming?"Loading temporary dataset…":"");const [error,setError]=useState("");const [notice,setNotice]=useState("");const [confirm,setConfirm]=useState<"clear"|"replace">("clear");const dialog=useRef<HTMLDialogElement>(null);const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(!incoming)return;const abort=new AbortController();const f={...initialFilters,view:['All','Concern','Attendance concern','Academic concern','Incomplete'].includes(incomingView)?incomingView:'All'};client.reviewStudents(incoming,abort.signal).then(async d=>{const full=await client.analyzeStudents(incoming,initialFilters,abort.signal);const shown=f.view==='All'?full:await client.analyzeStudents(incoming,f,abort.signal);if(!abort.signal.aborted){setDataset(d);setAll(full.students);setAnalysis(shown);setFilters(f);setApplied(f);}}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof APIError?e.message:'Cannot load this temporary dataset.');}).finally(()=>{if(!abort.signal.aborted)setBusy('');});return()=>abort.abort();},[incoming,incomingView,client]);
 async function run(label:string,work:()=>Promise<void>){setBusy(label);setError("");setNotice("");try{await work();}catch(e){if(e instanceof APIError){setError(e.status===422?"The file or mapping is not usable. Review the selected sheet, header row, identity, marks scale and attendance columns. Correct invalid values in your source file and retry.":e.status===404?"This temporary dataset has expired or is unavailable. Clear this view and upload it again.":e.message);}else setError("Student Analytics could not complete this operation. Try again.");}finally{setBusy("");}}
 function reset(){setBook(null);setFile(null);setPreview(null);setMapping(null);setDataset(null);setAnalysis(null);setAll([]);setDetail(null);setPage(0);setFilters(initialFilters);setApplied(initialFilters);if(input.current)input.current.value="";}
 async function previewBook(handle:string,selected:string,row:number){const p=await client.previewStudents(handle,selected,row);setPreview(p);const choice=(role:string)=>p.suggestions[role]?.candidates.length===1?p.suggestions[role].candidates[0]:null;setMapping({sheet:selected,header_row:row,student_id:choice("student_id"),student_name:choice("student_name"),attendance:choice("attendance")??"",attendance_scale:"auto",assessment_number:null,assessments:(p.suggestions.assessments?.candidates??[]).map(column=>({column,name:column,scale:"percentage",maximum:null}))});}
 async function upload(f:File){if(!/\.(csv|xlsx)$/i.test(f.name)){setError("Choose a CSV or XLSX file. Macro-enabled spreadsheets are not supported.");return;}if(f.size>10*1024*1024){setError("Choose a file no larger than 10 MB.");return;}await run("Parsing spreadsheet…",async()=>{const b=await client.uploadStudents(f);setBook(b);setFile(f);setSheet(b.sheets[0]);setHeader(1);await previewBook(b.handle,b.sheets[0],1);});}
 function requestClear(action:"clear"|"replace"){setConfirm(action);dialog.current?.showModal();}
 async function clear(){dialog.current?.close();await run("Clearing temporary dataset…",async()=>{const h=dataset?.handle??book?.handle;if(h){try{await client.clearStudents(h);}catch(e){if(!(e instanceof APIError&&e.status===404))throw e;}}reset();setNotice(confirm==="replace"?"Previous temporary dataset cleared. Choose a replacement spreadsheet.":"Temporary dataset cleared, including dependent assistant plans.");});}
 async function normalize(){if(!book||!mapping)return;await run("Validating and normalizing locally…",async()=>{const d=await client.normalizeStudents(book.handle,mapping);setDataset(d);setBook(null);setPreview(null);setMapping(null);if(d.validation.eligible_rows>0){const a=await client.analyzeStudents(d.handle,initialFilters);setAnalysis(a);setAll(a.students);setApplied(initialFilters);setFilters(initialFilters);}else setNotice("No eligible student rows. Review validation issues, clear this dataset and upload a corrected file.");});}
 async function analyze(){if(!dataset)return;await run("Applying deterministic thresholds and filters…",async()=>{const a=await client.analyzeStudents(dataset.handle,filters);setAnalysis(a);setApplied({...filters});setDetail(null);setPage(0);});}
 async function download(){if(!dataset)return;await run("Preparing filtered CSV…",async()=>{const blob=await client.exportStudents(dataset.handle,applied);const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="student-analytics.csv";link.click();URL.revokeObjectURL(url);setNotice("CSV exported for the applied view and thresholds.");});}
 const rows=[...(analysis?.students??[])].sort((a,b)=>{const x=a[sort],y=b[sort];if(x===null)return 1;if(y===null)return -1;return typeof x==="number"&&typeof y==="number"?y-x:value(x).localeCompare(value(y));});
 const select=(label:string,key:"student_id"|"student_name"|"attendance"|"assessment_number")=><label>{label}<select aria-label={label} value={mapping?.[key]??""} onChange={e=>setMapping(m=>m?{...m,[key]:e.target.value||null}:m)}><option value="">{key==="attendance"?"Select a column":"Not mapped"}</option>{preview?.columns.map(c=><option key={c}>{c}</option>)}</select></label>;
 if(!auth.ready)return <Loading label="Verifying your professor session…"/>;
 return <><PageHeading eyebrow="Private class workspace" title="Student Analytics" description="Inspect and analyze temporary student spreadsheets. Calculations stay local and deterministic; student records are never sent to AI."/>
 <p className="status-strip">Session-only data: refreshing this page loses the workspace link. Clear data explicitly when finished. Logout removes your server workspaces.</p>
 {error&&<ErrorNotice message={error}/>} {notice&&<p role="status">{notice}</p>}{busy&&<Loading label={busy}/>}
 <section className="panel"><h2>{dataset?"Current dataset":"Upload a student dataset"}</h2>{file&&<p>{file.name} · {Math.ceil(file.size/1024)} KB · {file.name.split(".").pop()?.toUpperCase()}</p>}
 <label className={book||dataset?"sr-only":""}>Student spreadsheet (CSV or XLSX, maximum 10 MB)<input ref={input} type="file" accept=".csv,.xlsx" disabled={!!busy||!!book||!!dataset} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/></label>
 {(book||dataset)&&<div className="student-actions"><button className="button secondary" disabled={!!busy} onClick={()=>requestClear("replace")}>Replace dataset</button><button className="button secondary" disabled={!!busy} onClick={()=>requestClear("clear")}>Clear dataset</button></div>}
 {book&&<><div className="student-controls"><label>Worksheet<select aria-label="Worksheet" value={sheet} disabled={!!busy} onChange={e=>{setSheet(e.target.value);setPreview(null);setMapping(null);}}>{book.sheets.map(s=><option key={s}>{s}</option>)}</select></label><label>Header row<input type="number" min="1" max="10020" value={header} onChange={e=>setHeader(Number(e.target.value))}/></label><button className="button secondary" disabled={!!busy} onClick={()=>void run("Loading bounded preview…",()=>previewBook(book.handle,sheet,header))}>Review selected header</button></div>
 {preview&&mapping&&<><h3>Data preview</h3><p>First {preview.rows.length} of {preview.total_rows} rows; cell previews are limited to 200 characters. Suggestions are deterministic and must be reviewed.</p><div className="table-scroll"><table><caption className="sr-only">Bounded spreadsheet preview</caption><thead><tr>{preview.columns.map(c=><th key={c} scope="col">{c}</th>)}</tr></thead><tbody>{preview.rows.map((row,i)=><tr key={i}>{preview.columns.map(c=><td key={c}>{value(row[c])}</td>)}</tr>)}</tbody></table></div>
 <h3>Confirm column mapping</h3><div className="student-controls">{select("Student identifier / roll number","student_id")}{select("Student name","student_name")}{select("Attendance column","attendance")}{select("Assessment number (trend only)","assessment_number")}<label>Attendance scale<select aria-label="Attendance scale" value={mapping.attendance_scale} onChange={e=>setMapping({...mapping,attendance_scale:e.target.value})}><option value="auto">Auto: percent or fraction</option><option value="percentage">Percentage</option><option value="fraction">Fraction (0–1)</option></select></label></div>
 <fieldset><legend>Assessment marks columns</legend>{preview.columns.map(c=>{const a=mapping.assessments.find(a=>a.column===c);return <div className="student-mark" key={c}><label><input type="checkbox" checked={!!a} onChange={e=>setMapping({...mapping,assessments:e.target.checked?[...mapping.assessments,{column:c,name:c,scale:"percentage",maximum:null}]:mapping.assessments.filter(a=>a.column!==c)})}/>{c}</label>{a&&<><label>Scale for {c}<select aria-label={`Scale for ${c}`} value={a.scale} onChange={e=>setMapping({...mapping,assessments:mapping.assessments.map(x=>x.column===c?{...x,scale:e.target.value}:x)})}><option value="percentage">Percentage (0–100)</option><option value="raw">Raw marks with maximum</option></select></label>{a.scale==="raw"&&<label>Maximum for {c}<input type="number" min="0.01" step="any" value={a.maximum??""} onChange={e=>setMapping({...mapping,assessments:mapping.assessments.map(x=>x.column===c?{...x,maximum:Number(e.target.value)}:x)})}/></label>}</>}</div>;})}</fieldset><p>Map at least one identity column, attendance, and marks. Trend input requires exactly one marks column and an assessment number.</p><button className="button primary" disabled={!!busy||!mapping.attendance||(!mapping.student_id&&!mapping.student_name)||!mapping.assessments.length} onClick={()=>void normalize()}>Validate and analyze</button></>}
 </>}
 {!book&&!dataset&&<p>No dataset loaded. Use fictional data for testing; use only student records you are authorized to process.</p>}
 </section>
 {dataset&&<section className="panel"><h2>Validation and data quality</h2><p>{dataset.validation.eligible_rows} eligible rows · {dataset.validation.invalid_rows} invalid rows excluded · {dataset.validation.incomplete_rows} incomplete rows · {dataset.validation.excluded_rows} summary rows excluded.</p><p>Invalid records are not analyzed. Missing values stay missing, never zero. Correct excluded records in your source file.</p>{dataset.issues.length>0&&<ul>{dataset.issues.map((i,n)=><li key={n}>Row {i.row}: {issueLabels[i.code]??"Review mapped data"} ({i.severity.toLowerCase()})</li>)}</ul>}<p>Up to 50 validation issues are shown; counts include the full dataset.</p></section>}
 {analysis&&dataset&&<><section className="panel"><h2>Class Overview</h2><div className="summary-grid">{[["Students",analysis.summary.total_students],["Average performance",analysis.summary.class_average_marks],["Average attendance",analysis.summary.average_attendance],["Requiring attention",analysis.summary.academic_concerns],["Incomplete records",analysis.summary.incomplete_data]].map(([label,v])=><div key={String(label)}><strong>{typeof v==="number"?Number.isInteger(v)?v:v.toFixed(2):value(v)}</strong><span>{String(label)}</span></div>)}</div><p>{value(analysis.summary.averages_basis)}. Marks available for {value(analysis.summary.marks_available_count)}; attendance available for {value(analysis.summary.attendance_available_count)} students.</p><p>{analysis.summary.mode==="trend"?"Trend mode: changes use ordered assessments and existing deterministic rules. Insufficient histories are labelled explicitly.":"Snapshot mode: no assessment history is available. Trends are unavailable."}</p></section>
 <section className="panel"><h2>Students</h2><form onSubmit={e=>{e.preventDefault();void analyze();}} className="student-controls"><label>Search identifier or name<input maxLength={200} value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></label><label>Student filter<select aria-label="Student filter" value={filters.view} onChange={e=>setFilters({...filters,view:e.target.value})}>{["All","Concern","Attendance concern","Academic concern","Incomplete"].map(v=><option key={v} value={v}>{v==="Concern"?"Requires attention":v}</option>)}</select></label><label>Marks attention threshold<input type="number" min="0" step="any" value={filters.marks_threshold} onChange={e=>setFilters({...filters,marks_threshold:Number(e.target.value)})}/></label><label>Attendance attention threshold<input type="number" min="0" max="100" step="any" value={filters.attendance_threshold} onChange={e=>setFilters({...filters,attendance_threshold:Number(e.target.value)})}/></label><button className="button secondary" disabled={!!busy}>Apply filters and thresholds</button></form><div className="student-actions"><label>Sort displayed students<select aria-label="Sort displayed students" value={sort} onChange={e=>{setSort(e.target.value);setPage(0);}}>{[["student_id","Identifier"],["student_name","Name"],["latest_marks","Performance (high first)"],["attendance","Attendance (high first)"]].map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><button className="button secondary" disabled={!!busy} onClick={()=>void download()}>Export applied view CSV</button></div><p>{rows.length} displayed. Export uses the applied search, filter and thresholds; pending control changes require Apply. Sort changes display order only. Exports include all matching rows across pages.</p>
 <div className="table-scroll"><table><caption>Student performance and attendance, with deterministic attention reasons</caption><thead><tr>{["Identifier","Name","Performance %","Attendance %","Status","Reason","Detail"].map(c=><th scope="col" key={c}>{c}</th>)}</tr></thead><tbody>{rows.slice(page*50,(page+1)*50).map((row,i)=><tr key={i}><td>{value(row.student_id)}</td><td>{value(row.student_name)}</td><td>{value(row.latest_marks)}{typeof row.latest_marks==="number"&&<meter className="student-meter" min={0} max={100} value={row.latest_marks} aria-label={`Performance ${row.latest_marks}%`}/>}</td><td>{value(row.attendance)}{typeof row.attendance==="number"&&<meter className="student-meter" min={0} max={100} value={row.attendance} aria-label={`Attendance ${row.attendance}%`}/>}</td><td>{value(row.incomplete_data?(row.needs_support?"Requires attention + incomplete":"Incomplete") : row.needs_support?"Requires attention":"No current concerns")}</td><td>{value(row.reasons)}</td><td><button className="button secondary" disabled={!!busy} aria-label={`View student ${page*50+i+1}`} onClick={()=>void run("Loading local student detail…",async()=>{const index=all.findIndex(a=>a.analysis_id===row.analysis_id);setDetail(await client.studentDetail(dataset.handle,index,applied));})}>View</button></td></tr>)}</tbody></table></div>{rows.length>50&&<div className="student-actions"><button className="button secondary" disabled={page===0} onClick={()=>setPage(page-1)}>Previous students</button><span>Page {page+1} of {Math.ceil(rows.length/50)} · 50 rows per page</span><button className="button secondary" disabled={(page+1)*50>=rows.length} onClick={()=>setPage(page+1)}>Next students</button></div>}{!rows.length&&<p>No students match the applied view.</p>}
 </section>{detail&&<section className="panel" aria-label="Student detail"><h2>Student detail</h2><button className="button secondary" onClick={()=>setDetail(null)}>Close detail</button><p>{value(detail.student.student_name)} · {value(detail.student.student_id)}</p><p>{value(detail.student.reasons)}</p><p>Performance trend: {value(detail.student.marks_trend)}. Attendance trend: {value(detail.student.attendance_trend)}.</p><div className="table-scroll"><table><caption>{detail.mode==="trend"?"Available assessment history":"Snapshot marks and attendance"}</caption><thead><tr>{Object.keys(detail.history[0]??{}).filter(k=>!k.startsWith("analysis_")).map(k=><th scope="col" key={k}>{k.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{detail.history.map((row,i)=><tr key={i}>{Object.entries(row).filter(([k])=>!k.startsWith("analysis_")).map(([k,v])=><td key={k}>{value(v)}</td>)}</tr>)}</tbody></table></div></section>}</>}
 <dialog ref={dialog} aria-labelledby="student-confirm-title" className="student-dialog"><h2 id="student-confirm-title">{confirm==="replace"?"Replace this dataset?":"Clear this dataset?"}</h2><p>The temporary dataset and its dependent assistant plans will be removed. This does not delete your source spreadsheet.</p><div className="student-actions"><button className="button secondary" onClick={()=>dialog.current?.close()}>Keep dataset</button><button className="button secondary" onClick={()=>void clear()}>{confirm==="replace"?"Confirm replacement":"Confirm clear"}</button></div></dialog>
 </>;
}
